packages/playground-vue/src/App.vue, packages/playground-vue/src/components/Card.vue, packages/playground-vue/src/components/Demo/CheckboxDemo.vue, packages/playground-vue/src/components/Demo/SwitchDemo.vue, packages/radix-vue/dev/App.vue, packages/radix-vue/src/Switch/SwitchRoot.vue, packages/radix-vue/src/Switch/SwitchThumb.vue, packages/radix-vue/src/Switch/index.ts, packages/radix-vue/src/index.ts
=> Feat: Switch(Phase 1/3)

README.md, packages/playground-vue/src/App.vue, packages/playground-vue/src/components/Demo/SeparatorDemo.vue, packages/radix-vue/src/Separator/Separator.vue, packages/radix-vue/src/Separator/index.ts, packages/radix-vue/src/index.ts
=> Feat: Separator (1/3)

README.md, packages/playground-vue/package.json, packages/playground-vue/src/App.vue, packages/playground-vue/src/components/Demo/ToggleDemo.vue, packages/playground-vue/tailwind.config.js, packages/radix-vue/src/Toggle/Toggle.vue, packages/radix-vue/src/Toggle/index.ts, packages/radix-vue/src/index.ts, pnpm-lock.yaml
=> Feat:Toggle(1/3)

README.md, packages/playground-vue/src/App.vue, packages/playground-vue/src/components/Demo/ToggleDemo.vue, packages/playground-vue/src/components/Demo/ToggleGroupDemo.vue, packages/radix-vue/src/ToggleGroup/ToggleGroupItem.vue, packages/radix-vue/src/ToggleGroup/ToggleGroupRoot.vue, packages/radix-vue/src/ToggleGroup/index.ts, packages/radix-vue/src/index.ts
=> Feat: ToggleGroup (1/3)

packages/playground-vue/src/App.vue, packages/playground-vue/src/components/Demo/AspectRatioDemo.vue, packages/radix-vue/src/AspectRatio/AspectRatio.vue, packages/radix-vue/src/AspectRatio/index.ts, packages/radix-vue/src/index.ts
=> Feat: Aspect 2/3

README.md, packages/playground-vue/src/App.vue, packages/playground-vue/src/components/Demo/TabsDemo.vue, packages/playground-vue/tailwind.config.js, packages/radix-vue/src/Tabs/TabsContent.vue, packages/radix-vue/src/Tabs/TabsList.vue, packages/radix-vue/src/Tabs/TabsRoot.vue, packages/radix-vue/src/Tabs/TabsTrigger.vue, packages/radix-vue/src/Tabs/index.ts, packages/radix-vue/src/ToggleGroup/ToggleGroupItem.vue, packages/radix-vue/src/index.ts, packages/radix-vue/src/shared/types.ts
=> Feat: Tabs(1/3)

packages/playground-vue/src/App.vue, packages/playground-vue/src/components/Demo/SliderDemo.vue, packages/radix-vue/src/Slider/SliderRange.vue, packages/radix-vue/src/Slider/SliderRoot.vue, packages/radix-vue/src/Slider/SliderThumb.vue, packages/radix-vue/src/Slider/SliderTrack.vue, packages/radix-vue/src/Slider/index.ts, packages/radix-vue/src/Tabs/TabsTrigger.vue, packages/radix-vue/src/index.ts, packages/radix-vue/src/shared/types.ts
=> Feat: Slider (1/3)

README.md, packages/playground-vue/src/App.vue, packages/playground-vue/src/components/Demo/ProgressDemo.vue, packages/radix-vue/src/Progress/ProgressIndicator.vue, packages/radix-vue/src/Progress/ProgressRoot.vue, packages/radix-vue/src/Progress/index.ts, packages/radix-vue/src/Slider/SliderRoot.vue, packages/radix-vue/src/Slider/SliderThumb.vue, packages/radix-vue/src/index.ts
=> Feat: Progress (1/3)

packages/playground-vue/src/App.vue, packages/playground-vue/src/components/Demo/CollapsibleDemo.vue
=> Refactor: Collapsible Demo

packages/playground-vue/src/App.vue, packages/radix-vue/src/Avatar/AvatarFallback.vue, packages/radix-vue/src/Avatar/AvatarImage.vue, packages/radix-vue/src/Avatar/AvatarRoot.vue, packages/radix-vue/src/Avatar/index.ts, packages/radix-vue/src/index.ts
=> Feat: Avatar (1/3)

README.md, packages/playground-vue/src/App.vue, packages/playground-vue/src/components/Demo/PopoverDemo.vue, packages/radix-vue/src/AlertDialog/AlertDialogContent.vue, packages/radix-vue/src/Dialog/DialogContent.vue, packages/radix-vue/src/Popover/PopoverAnchor.vue, packages/radix-vue/src/Popover/PopoverArrow.vue, packages/radix-vue/src/Popover/PopoverClose.vue, packages/radix-vue/src/Popover/PopoverContent.vue, packages/radix-vue/src/Popover/PopoverPortal.vue, packages/radix-vue/src/Popover/PopoverRoot.vue, packages/radix-vue/src/Popover/PopoverTrigger.vue, packages/radix-vue/src/Popover/index.ts, packages/radix-vue/src/index.ts, packages/radix-vue/src/shared/trap-focus.ts, packages/radix-vue/src/shared/useClickOutside.ts
=> Feat: Popover (1/3)

packages/playground-vue/src/components/Demo/CheckboxDemo.vue, packages/radix-vue/src/Checkbox/CheckboxIndicator.vue, packages/radix-vue/src/Checkbox/CheckboxRoot.vue, packages/radix-vue/src/HoverCard/HoverCardContent.vue
=> refactor:checkbox to use InjectionKey

packages/playground-vue/src/components/Demo/DropdownMenuDemo.vue, packages/playground-vue/src/components/Demo/HoverCardDemo.vue, packages/playground-vue/src/components/Demo/PopoverDemo.vue, packages/playground-vue/src/components/Demo/TooltipDemo.vue, packages/radix-vue/src/DropdownMenu/DropdownMenuArrow.vue, packages/radix-vue/src/DropdownMenu/DropdownMenuContent.vue, packages/radix-vue/src/HoverCard/HoverCardArrow.vue, packages/radix-vue/src/HoverCard/HoverCardContent.vue, packages/radix-vue/src/Popover/PopoverArrow.vue, packages/radix-vue/src/Popover/PopoverContent.vue, packages/radix-vue/src/Tooltip/TooltipArrow.vue, packages/radix-vue/src/Tooltip/TooltipContent.vue
=> fix: add arrow

packages/radix-vue/src/HoverCard/HoverCardTrigger.vue, packages/radix-vue/src/Tooltip/TooltipTrigger.vue, packages/radix-vue/src/shared/index.ts, packages/radix-vue/src/shared/useArrowNavigation.ts, packages/radix-vue/src/shared/useHoverDelay.ts, packages/radix-vue/src/shared/useMouseInElement.ts
all delay on open, still very buggy sometimes dont open
#11 #28
=> fix[tooltip, hovercard]: usehoverdelay

README.md, packages/playground-vue/src/App.vue, packages/playground-vue/src/components/Demo/ContextMenuDemo.vue, packages/radix-vue/src/ContextMenu/ContextMenuArrow.vue, packages/radix-vue/src/ContextMenu/ContextMenuCheckboxItem.vue, packages/radix-vue/src/ContextMenu/ContextMenuContent.vue, packages/radix-vue/src/ContextMenu/ContextMenuGroup.vue, packages/radix-vue/src/ContextMenu/ContextMenuItem.vue, packages/radix-vue/src/ContextMenu/ContextMenuItemIndicator.vue, packages/radix-vue/src/ContextMenu/ContextMenuLabel.vue, packages/radix-vue/src/ContextMenu/ContextMenuPortal.vue, packages/radix-vue/src/ContextMenu/ContextMenuRadioGroup.vue, packages/radix-vue/src/ContextMenu/ContextMenuRadioItem.vue, packages/radix-vue/src/ContextMenu/ContextMenuRoot.vue, packages/radix-vue/src/ContextMenu/ContextMenuSeparator.vue, packages/radix-vue/src/ContextMenu/ContextMenuTrigger.vue, packages/radix-vue/src/ContextMenu/index.ts, packages/radix-vue/src/index.ts
=> Feat: Context Menu (1/3)

README.md, packages/radix-vue/src/DropdownMenu/DropdownMenuItem.vue, packages/radix-vue/src/Popover/PopoverContent.vue, packages/radix-vue/src/Progress/ProgressIndicator.vue, packages/radix-vue/src/Progress/ProgressRoot.vue, packages/radix-vue/src/RadioGroup/RadioGroupItem.vue, packages/radix-vue/src/Slider/SliderRange.vue, packages/radix-vue/src/Slider/SliderRoot.vue, packages/radix-vue/src/Slider/SliderThumb.vue, packages/radix-vue/src/Switch/SwitchRoot.vue, packages/radix-vue/src/Switch/SwitchThumb.vue, packages/radix-vue/src/Tabs/TabsRoot.vue, packages/radix-vue/src/Tabs/TabsTrigger.vue, packages/radix-vue/src/ToggleGroup/ToggleGroupItem.vue, packages/radix-vue/src/ToggleGroup/ToggleGroupRoot.vue, packages/radix-vue/src/Toolbar/ToolbarButton.vue, packages/radix-vue/src/Toolbar/ToolbarLink.vue, packages/radix-vue/src/Toolbar/ToolbarToggleItem.vue, packages/radix-vue/src/Tooltip/TooltipContent.vue, packages/radix-vue/src/Tooltip/TooltipRoot.vue, packages/radix-vue/src/shared/useArrowNavigation.ts
=> dev: refactor

packages/playground-vue/src/components/Demo/HoverCardDemo.vue, packages/playground-vue/src/components/Demo/SwitchDemo.vue, packages/radix-vue/src/HoverCard/HoverCardPortal.vue, packages/radix-vue/src/HoverCard/HoverCardRoot.vue, packages/radix-vue/src/HoverCard/HoverCardTrigger.vue, packages/radix-vue/src/shared/component/BasePortal.vue
enable hovercard without v-model
#11
=> Feat: Hover Card (2/3)

pnpm-lock.yaml
add test directory and create first test
=> init test dir

packages/radix-vue/src/HoverCard/HoverCardContent.vue, packages/radix-vue/src/HoverCard/HoverCardRoot.vue, packages/radix-vue/src/HoverCard/HoverCardTrigger.vue, packages/radix-vue/src/shared/component/BaseToggle.vue, packages/radix-vue/src/shared/index.ts, packages/radix-vue/src/shared/useHoverDelay.ts, packages/radix-vue/src/shared/useMouseleaveDelay.ts
=> Fix hover delay

packages/radix-vue/src/Switch/SwitchRoot.vue, playground/vue3/src/components/Demo/SwitchDemo.vue
make switch controllable via v-model or uncontrolled(works without v-model)
#22
=> fix: make switch controllable and unctrollable

packages/radix-vue/src/AlertDialog/AlertDialogContent.vue, packages/radix-vue/src/AlertDialog/AlertDialogRoot.vue, packages/radix-vue/src/AlertDialog/AlertDialogTrigger.vue, packages/radix-vue/src/Collapsible/CollapsibleRoot.vue, packages/radix-vue/src/Dialog/DialogContent.vue, packages/radix-vue/src/Dialog/DialogRoot.vue, packages/radix-vue/src/Dialog/DialogTrigger.vue, playground/vue3/src/components/Demo/AlertDialogDemo.vue, playground/vue3/src/components/Demo/CollapsibleDemo.vue, playground/vue3/src/components/Demo/DialogDemo.vue
=> feat: improve open defaultopen and onopenchange

playground/vue3/src/App.vue, pnpm-lock.yaml
thank god for chatgpt
https://chat.openai.com/share/4b7f9351-620c-44b6-9501-1c6b9d0d3a23
=> dev: refactor playground to sort components alphabetically.

packages/radix-vue/package.json, packages/radix-vue/src/ContextMenu/ContextMenuCheckboxItem.vue, packages/radix-vue/src/ContextMenu/ContextMenuItem.vue, packages/radix-vue/src/ContextMenu/ContextMenuRadioItem.vue, packages/radix-vue/src/ContextMenu/ContextMenuRoot.vue, packages/radix-vue/src/ContextMenu/ContextMenuTrigger.vue, packages/radix-vue/src/DropdownMenu/DropdownMenuArrow.vue, packages/radix-vue/src/DropdownMenu/DropdownMenuContent.vue, packages/radix-vue/src/DropdownMenu/DropdownMenuSubContent.vue, packages/radix-vue/src/DropdownMenu/DropdownMenuSubTrigger.vue, packages/radix-vue/src/Popover/PopoverArrow.vue, packages/radix-vue/src/Slider/SliderThumb.vue, packages/radix-vue/src/Toolbar/ToolbarToggleGroup.vue, packages/radix-vue/src/shared/component/BaseMenuItem.vue, packages/radix-vue/src/shared/trap-focus.ts, packages/radix-vue/src/shared/useHoverDelay.ts, packages/radix-vue/src/shared/useMouseleaveDelay.ts, packages/radix-vue/tsconfig.app.json, packages/radix-vue/tsconfig.json, pnpm-lock.yaml
- fix all the types issue (some was @ts-expect-error)
- fix build to emit type declaration correctly
=> fix: type declaration missing

README.md
Add '⏳' to ScrollArea and Select
=> chore: update todo item progress

packages/radix-vue/src/ScrollArea/index.ts, playground/vue3/src/components/Demo/ScrollAreaDemo.vue, pnpm-lock.yaml
=> fix: scroll viewport export name

packages/radix-vue/src/Popover/PopoverContent.vue, playground/vue3/src/components/Demo/PopoverDemo.vue
add prop 'side' to PopoverContent
=> [Popover]feat: add side prop

packages/radix-vue/src/Collapsible/CollapsibleContent.vue
add a state to indicate if there's animation present in the element.
If `no`, we would immediately set `isPresent.value` false as there's no event listener of `animationend`
=> fix: isPresent still true when no animation is provide

docs/content/1.overview/1.introduction.md, docs/content/1.overview/2.getting-started.md, docs/content/1.overview/3.accessibility.md
Update overview section to fit Radix Vue
=> [Docs] Overview section

packages/radix-vue/package.json, packages/radix-vue/vitest.config.ts, pnpm-lock.yaml
This PR adds component testing integration to improve components stability.
No specific related issue. This PR aims to improve the overall testing capabilities of the project.
Component testing integration is essential to ensure the stability and reliability of compnents. By adding comprehensive component tests, we can identify and fix any potential issues or regressions, providing a more robust and dependable user experience. This PR will enhance the project's quality by improving test coverage.
=> test: components testing integration

packages/radix-vue/src/Menubar/MenubarArrow.vue, packages/radix-vue/src/Menubar/MenubarCheckboxItem.vue, packages/radix-vue/src/Menubar/MenubarContent.vue, packages/radix-vue/src/Menubar/MenubarGroup.vue, packages/radix-vue/src/Menubar/MenubarItem.vue, packages/radix-vue/src/Menubar/MenubarItemIndicator.vue, packages/radix-vue/src/Menubar/MenubarLabel.vue, packages/radix-vue/src/Menubar/MenubarMenu.vue, packages/radix-vue/src/Menubar/MenubarPortal.vue, packages/radix-vue/src/Menubar/MenubarRadioGroup.vue, packages/radix-vue/src/Menubar/MenubarRadioItem.vue, packages/radix-vue/src/Menubar/MenubarRoot.vue, packages/radix-vue/src/Menubar/MenubarSeparator.vue, packages/radix-vue/src/Menubar/MenubarSub.vue, packages/radix-vue/src/Menubar/MenubarSubContent.vue, packages/radix-vue/src/Menubar/MenubarSubTrigger.vue, packages/radix-vue/src/Menubar/MenubarTrigger.vue, packages/radix-vue/src/Menubar/index.ts, packages/radix-vue/src/Menubar/utils.ts, packages/radix-vue/src/index.ts, packages/radix-vue/src/shared/component/BaseMenuItem.vue, playground/vue3/src/App.vue, playground/vue3/src/components/Demo/MenubarDemo.vue, pnpm-lock.yaml
=> [Menubar]feat: 1/3

packages/radix-vue/src/Menubar/MenubarSubTrigger.vue, packages/radix-vue/src/Menubar/MenubarTrigger.vue
=> [Menubar]fix: fix several issues

docs/components/content/tables/CssVariablesTable.vue, docs/components/content/tables/PropsTable.vue, docs/content/1.overview/2.getting-started.md, docs/content/3.components/accordion.md, docs/content/3.components/alert-dialog.md, docs/content/3.components/aspect-ratio.md, docs/content/3.components/avatar.md, docs/content/3.components/checkbox.md, docs/content/3.components/collapsible.md, docs/content/3.components/context-menu.md, docs/content/3.components/dialog.md, docs/content/3.components/dropdown-menu.md, docs/content/3.components/form.md, docs/content/3.components/hover-card.md, docs/content/3.components/label.md, docs/content/3.components/popover.md, docs/content/3.components/progress.md, docs/content/3.components/radio-group.md, docs/content/3.components/scroll-area.md, docs/content/3.components/separator.md, docs/content/3.components/slider.md, docs/content/3.components/switch.md, docs/content/3.components/tabs.md, docs/content/3.components/toggle-group.md, docs/content/3.components/toggle.md, docs/content/3.components/tooltip.md, docs/nuxt.config.ts
- add `CssVariablesTable.vue`
- add prefix to demo components, sovles #161
=> Docs zernonia

packages/radix-vue/src/Collapsible/CollapsibleContent.vue, packages/radix-vue/src/Collapsible/CollapsibleRoot.vue, packages/radix-vue/src/Collapsible/CollapsibleTrigger.vue, playground/vue3/src/components/Demo/CollapsibleDemo.vue, playground/vue3/src/components/Demo/ContextMenuDemo.vue, playground/vue3/src/components/Demo/TabsDemo.vue
=> [Collapsible]feat: 2/3

README.md, packages/radix-vue/src/ToggleGroup/ToggleGroupItem.vue, packages/radix-vue/src/ToggleGroup/ToggleGroupRoot.vue, playground/vue3/src/components/Demo/ToggleGroupDemo.vue
=> [Toggle Group]feat: 2/3

README.md, packages/radix-vue/src/RadioGroup/RadioGroupIndicator.vue, packages/radix-vue/src/RadioGroup/RadioGroupItem.vue, packages/radix-vue/src/RadioGroup/RadioGroupRoot.vue, packages/radix-vue/src/Tabs/TabsTrigger.vue, packages/radix-vue/src/shared/useArrowNavigation.test.ts, packages/radix-vue/src/shared/useArrowNavigation.ts, playground/vue3/src/components/Demo/RadioGroupDemo.vue, pnpm-lock.yaml
Implemented `RadioGroup` components
Using the [Radix API](https://www.radix-ui.com/docs/primitives/components/radio-group#content)
See #140
Someone has to do it duh
Just the playground and multiple demos using this component
=> Radio Group

packages/radix-vue/src/ScrollArea/ScrollAreaScrollbar.vue, packages/radix-vue/src/ScrollArea/ScrollAreaScrollbarAuto.vue, packages/radix-vue/src/ScrollArea/ScrollAreaScrollbarHover.vue, packages/radix-vue/src/ScrollArea/ScrollAreaScrollbarImpl.vue, packages/radix-vue/src/ScrollArea/ScrollAreaScrollbarX.vue
fix the scrollbar showing when it shouldn't
=> [Bug] ScrollArea showing scrollbar when the `type=hover`

README.md, packages/radix-vue/src/Progress/ProgressIndicator.vue, packages/radix-vue/src/Progress/ProgressRoot.vue, playground/vue3/pnpm-lock.yaml, playground/vue3/src/components/Demo/ProgressDemo.vue, playground/vue3/src/components/stories/Progress.story.vue
I completed the API from Radix as well as created multiple variants in the playground
In `ProgressRoot`:
- I created `modelValue` using `useVModel`. This value is set by the user, we watch and validate the changes (`validateValue`). By default this value is `null`, which will make the state of the progress as `indeterminate`
- I created `max` model using `useVModel`. This value is set by the user, we watch and validate the changes (`validateMax`). By default this value is `100`.
- I also created a bunch of stories that I think are relevant for the future which will help us to debug and maintain the component. There is a small issue in the story, where I use `setInterval` and for some reason is being triggered twice every tick. I do not bother to fix this issue, since is not relevant for …
=> [Progress]feat: 2/3

docs/content/components/collapsible.md, docs/content/components/context-menu.md, docs/content/components/dialog.md, docs/content/components/dropdown-menu.md, docs/content/components/menubar.md, docs/content/components/navigation-menu.md, docs/content/components/radio-group.md, docs/content/components/tabs.md
https://github.com/radix-vue/radix-vue/issues/206
=> new-docs: fixes + updates

packages/radix-vue/src/Switch/SwitchRoot.vue, packages/radix-vue/src/Switch/SwitchThumb.vue, packages/radix-vue/src/Switch/__tests__/Switch.test.ts, packages/radix-vue/src/Switch/__tests__/Switch1.vue, playground/vue3/src/components/Demo/SwitchDemo.vue, pnpm-lock.yaml
=> [Switch]fix: fix space keydown behavior and role

packages/radix-vue/src/Primitive/Primitive.vue, packages/radix-vue/src/shared/index.ts, packages/radix-vue/src/shared/isValidVNodeElement.ts
The previous Primitive wasn't complete.
Taken inpsiration from Ark-UI to implement Primitive
=> [Bug]: Tooltip trigger aschild doesnt work

docs/content/components/aspect-ratio.md, docs/content/components/avatar.md, docs/content/components/context-menu.md, docs/content/components/dropdown-menu.md, docs/content/components/menubar.md, docs/content/components/navigation-menu.md, docs/content/guides/styling.md, docs/content/overview/introduction.md, docs/content/overview/releases.md
Convert `jsx` to `vue` code in the doc's code snippets
- menubar
- context-menu
- dropdown-menu
- navigation-menu
https://github.com/radix-vue/radix-vue/issues/206
=> New Docs: jsx code conversion

packages/radix-vue/src/Tooltip/TooltipTrigger.vue
=> Fix : tooltip open on keyboard focus

packages/radix-vue/src/AlertDialog/AlertDialogContent.vue
=> Fix : Alert Dialog handle click outside

packages/radix-vue/src/Primitive/Primitive.test.ts, packages/radix-vue/src/Primitive/Primitive.vue
Fixes https://github.com/radix-vue/radix-vue/issues/226
Added test to check
- asChild keep the props, if the props/attrs exist then replace the one inheritted.
- ... and previous bug
=> [Bug]: fix props not inheritted correctly

packages/radix-vue/src/AlertDialog/AlertDialogRoot.vue, packages/radix-vue/src/Dialog/DialogRoot.vue, packages/radix-vue/src/shared/index.ts, packages/radix-vue/src/shared/useBodyScrollLock.ts
=> fix: add margin-right to body to prevent content shift

packages/radix-vue/src/ContextMenu/ContextMenu.story.vue, packages/radix-vue/src/ContextMenu/ContextMenuArrow.vue, packages/radix-vue/src/ContextMenu/ContextMenuCheckboxItem.vue, packages/radix-vue/src/ContextMenu/ContextMenuContent.vue, packages/radix-vue/src/ContextMenu/ContextMenuGroup.vue, packages/radix-vue/src/ContextMenu/ContextMenuItem.vue, packages/radix-vue/src/ContextMenu/ContextMenuItemIndicator.vue, packages/radix-vue/src/ContextMenu/ContextMenuLabel.vue, packages/radix-vue/src/ContextMenu/ContextMenuPortal.vue, packages/radix-vue/src/ContextMenu/ContextMenuRadioGroup.vue, packages/radix-vue/src/ContextMenu/ContextMenuRadioItem.vue, packages/radix-vue/src/ContextMenu/ContextMenuRoot.vue, packages/radix-vue/src/ContextMenu/ContextMenuSeparator.vue, packages/radix-vue/src/ContextMenu/ContextMenuSub.vue, packages/radix-vue/src/ContextMenu/ContextMenuSubContent.vue, packages/radix-vue/src/ContextMenu/ContextMenuSubTrigger.vue, packages/radix-vue/src/ContextMenu/ContextMenuTrigger.vue, packages/radix-vue/src/ContextMenu/utils.ts, packages/radix-vue/src/Menu/MenuSubContent.vue, packages/radix-vue/src/Popper/PopperAnchor.vue, packages/radix-vue/src/Popper/PopperRoot.vue, packages/radix-vue/src/Select/SelectItem.vue, packages/radix-vue/src/shared/component/BaseMenuItem.vue, packages/radix-vue/src/shared/useEmitAsProps.ts, pnpm-lock.yaml
Branches of from https://github.com/radix-vue/radix-vue/pull/291
=> [Context menu] feat 2/3

packages/radix-vue/src/Menu/MenuItem.vue, packages/radix-vue/src/Menu/MenuItemImpl.vue
=> fix: provide primitive props for MenuItem

.vscode/settings.json
I don't know how you guys write tailwind without autocomplete and other intelisense features.
=> chore: tailwind intelisense for stories 

docs/components/demo/Switch/index.vue
update sample code to be correct prop on switch
=> Update Switch Docs

packages/radix-vue/src/Popper/PopperArrow.vue, packages/radix-vue/src/shared/component/Arrow.vue, pnpm-lock.yaml
#353 
:) first time contributing here! Looking forward to your kind corrections😊
=> bug: PopperArrow missing props as-child

packages/radix-vue/src/Slider/SliderThumbImpl.vue
=> refactor(slider): remove `<span>` wrapping the `<SliderThumb>`

docs/content/guides/composition.md
=> doc: update composition.md

docs/content/guides/styling.md
AccordtionItemProps -->   AccordionItemProps
=> docs: fix a typo 

packages/radix-vue/src/Presence/Presence.ts, packages/radix-vue/src/Tabs/TabsContent.vue
Maybe resolves (works for me, but not sure yet): https://discordapp.com/channels/1121805548782878813/1169341352807497779
I have also added ability to access `present` variable from v-slot.
=> fix: TabsContent appearance

docs/.vitepress/layouts/showcase.vue, docs/content/showcase.md
Hey @zernonia, I made the changes.
This PR does the following:
- Add [UI Thing](https://ui-thing.behonbaker.com/getting-started/introduction) to the list of packages on the showcase page
- Removes the UI Thing starter from the starter section
- Adds a conditional check for the list of starters. If the list is empty, hide the starter block all together
=> UI thing update

docs/components/demo/Menubar/tailwind/index.vue
Remove conflict css rules and incorrect rules for menubar
=> docs: fix conflict css rules in menubar

packages/radix-vue/src/Presence/Presence.ts
A tiny typo in Presence.ts error message.
=> Typo in Presence.ts error message

.github/ISSUE_TEMPLATE/bug-report.yml
Spotted a typo: Conext -> Context
=> fix(typo): update bug-report.yml

packages/radix-vue/src/Select/SelectItem.vue
Solving this issue: https://github.com/radix-vue/radix-vue/issues/578
=> Prevent touch event propagation on select

packages/radix-vue/constant/components.ts, packages/radix-vue/src/ConfigProvider/ConfigProvider.test.ts, packages/radix-vue/src/index.ts, packages/radix-vue/src/shared/useBodyScrollLock.test.ts, packages/radix-vue/src/shared/useBodyScrollLock.ts
=> fix: useBodyScrollLock is now using a singleton logic

packages/radix-vue/src/Toast/FocusProxy.vue
closes https://github.com/radix-vue/radix-vue/issues/679
=> fix(Toast): correct style attribute syntax

packages/radix-vue/src/DismissableLayer/story/DismissableLayerDialog.story.vue, packages/radix-vue/src/DismissableLayer/story/_DummyDialog.vue, packages/radix-vue/src/DismissableLayer/utils.ts
=> fix: invalid coords check in `usePointerDownOutside` composable

packages/radix-vue/src/Tooltip/TooltipContentImpl.vue, packages/radix-vue/src/Tooltip/TooltipRoot.vue, packages/radix-vue/src/Tooltip/TooltipTrigger.vue
https://github.com/radix-vue/radix-vue/issues/733
=> fix(tooltip): fix aria-describedby

packages/radix-vue/src/Toast/ToastViewport.vue
=> feat: make ToastViewport label prop take a function

packages/radix-vue/src/Tooltip/TooltipProvider.vue, packages/radix-vue/src/Tooltip/TooltipRoot.vue, packages/radix-vue/src/Tooltip/TooltipTrigger.vue
=> feat: added keyboard-focus-only prop to Tooltip

packages/radix-vue/package.json, pnpm-lock.yaml
=> fix: remove `@internationalized/date` from list of peer dependencies and make it just dependency

packages/radix-vue/namespaced.d.ts, packages/radix-vue/package.json, packages/radix-vue/resolver.d.ts
=> fix: type export error

docs/components/demo/Calendar/tailwind/tailwind.config.js, docs/components/demo/DateField/tailwind/tailwind.config.js, docs/components/demo/DatePicker/tailwind/tailwind.config.js, docs/components/demo/DateRangeField/tailwind/tailwind.config.js, docs/components/demo/DateRangePicker/tailwind/tailwind.config.js, docs/components/demo/RangeCalendar/tailwind/tailwind.config.js
=> chore: update tailwind.config for calendar components for setup correct repro

packages/radix-vue/src/Tooltip/TooltipTrigger.vue
=> fix: tooltip trigger listener binding

packages/radix-vue/src/Tabs/TabsRoot.vue
Hi 👋 Closes #819 
- Add generic type to TabsRoot component. 
- Update props for generic type
- Update v-model for generic type
https://github.com/radix-vue/radix-vue/assets/20302368/b87061a4-46e3-4a7c-957e-474b68986074
=> feat(Tabs): add generic v-model

docs/content/components/calendar.md, docs/content/components/date-picker.md, docs/content/components/date-range-picker.md, docs/content/components/range-calendar.md
=> docs: update

.github/workflows/pkg.pr.new.yaml, packages/radix-vue/README.md
Previously [#931](https://github.com/radix-vue/radix-vue/pull/931#issuecomment-2118886210)
https://github.com/stackblitz-labs/pkg.pr.new
=> ci: add `pkg.pr.new` workflow

packages/radix-vue/package.json, packages/radix-vue/src/index.ts, pnpm-lock.yaml
=> fix ts2742 error of Primitive

docs/content/guides/dates.md, packages/radix-vue/src/date/calendar.ts
Hello,
This PR adds a new function `createDateRange` to `radix-vue/date` for creating custom `DateValue` ranges for use in the `Calendar` components.
Also, it updates the `Dates` docs with the function and adds the `createMonth` function example.
=> Feat: export createDateRange function

packages/radix-vue/src/DateField/DateField.test.ts, packages/radix-vue/src/DateField/story/_DateField.vue, packages/radix-vue/src/DateField/useDateField.ts, packages/radix-vue/src/DateField/utils/segment.ts
=> fix(DateField): fix hour segment update by dayPeriod

packages/radix-vue/src/Combobox/ComboboxInput.vue, packages/radix-vue/src/Combobox/ComboboxItem.vue, packages/radix-vue/src/Combobox/ComboboxRoot.vue
=> fix(Combobox): move focus to options on keyboard navigation

packages/radix-vue/src/NumberField/NumberFieldDecrement.vue, packages/radix-vue/src/NumberField/NumberFieldIncrement.vue
resolving the infinite counting issue reported [here](https://github.com/radix-vue/radix-vue/issues/1006).
=> fix: infinite counting in `NumberFieldInput`

packages/radix-vue/src/Editable/Editable.test.ts, packages/radix-vue/src/Editable/EditableRoot.vue
=> fix(Editable): handle blur on submit mode both

packages/radix-vue/src/Menu/MenuItemImpl.vue
https://github.com/radix-ui/primitives/pull/2451
=> fix: don’t scroll menus in response to hover

packages/radix-vue/src/Menu/MenuContentImpl.vue, packages/radix-vue/src/RovingFocus/RovingFocusGroup.vue, packages/radix-vue/src/RovingFocus/utils.ts
https://github.com/radix-ui/primitives/pull/2762
=> fix: prevent scroll on initial menu focus

packages/radix-vue/src/Calendar/Calendar.test.ts
Hello,
The `fixedWeeks` test was updated as per @xollaborator 's comments here: https://github.com/radix-vue/radix-vue/pull/1029#discussion_r1650204989 to make it more robust.
=> fix(Calendar): make `fixedWeeks` test more robust

docs/content/components/toast.md
There two occurence of 2 spaces where one is enough
=> docs: remove useless space

packages/radix-vue/src/HoverCard/HoverCardTrigger.vue, packages/radix-vue/src/HoverCard/story/HoverMultiCard.story.vue, packages/radix-vue/src/Tooltip/TooltipTrigger.vue, packages/radix-vue/src/shared/useGraceArea.ts
closes https://github.com/radix-vue/radix-vue/issues/850
=> fix(HoverCard, Tooltip): overlapping because of grace area

docs/content/components/dialog.md
`aria-describedby="undefined}` --> `aria-describedby="undefined"`
=> docs(dialog): typo

packages/radix-vue/src/RangeCalendar/RangeCalendarGrid.vue
=> fix(RangeCalendar): fix readonly and disabled on grid

packages/radix-vue/src/DateField/useDateField.ts
=> fix(DateField): enable zeroes on hour field

docs/content/meta/StepperRoot.md, packages/radix-vue/src/Stepper/Stepper.test.ts, packages/radix-vue/src/Stepper/StepperRoot.vue, packages/radix-vue/src/Stepper/StepperTrigger.vue, packages/radix-vue/src/Stepper/story/StepperDefault.story.vue
=> feat(Stepper): implement slot utility functions

packages/radix-vue/src/Popper/PopperAnchor.vue
=> fix(Popper): use `watchEffect` for anchor update #1188

packages/radix-vue/src/DateField/DateFieldRoot.vue, packages/radix-vue/src/DateField/useDateField.ts, packages/radix-vue/src/DateField/utils/parser.ts, packages/radix-vue/src/DatePicker/DatePickerRoot.vue, packages/radix-vue/src/DateRangeField/DateRangeFieldRoot.vue, packages/radix-vue/src/DateRangePicker/DateRangePickerRoot.vue
=> fix(DateField): emit undefined on segment clear after input is filled

eslint.config.mjs
fix [#1218](https://github.com/radix-vue/radix-vue/issues/1218)
=> chore: update eslint config

packages/radix-vue/src/RangeCalendar/RangeCalendarRoot.vue
=> fix(RangeCalendar): update start value and end value on modelValue update

packages/radix-vue/src/shared/types.ts, packages/radix-vue/src/shared/useBodyScrollLock.ts
This PR fix #1319 
https://github.com/user-attachments/assets/1d0b8fad-25f7-4037-bce3-2cc4a9337ca8
=> fix(ConfigProvider): pass string to `ScrollBodyOption`

packages/radix-vue/src/Combobox/ComboboxRoot.vue, packages/radix-vue/src/Combobox/story/ComboboxScrolling.story.vue
Fixes #1327 
Also added a story to showcase and test highlighting behavior in a scrolling combobox.
=> fix(Combobox): defer highlighted item scrollIntoView

packages/radix-vue/src/ConfigProvider/ConfigProvider.vue, packages/radix-vue/src/Dialog/DialogRoot.vue, packages/radix-vue/src/Popper/PopperRoot.vue, packages/radix-vue/src/Select/SelectProvider.vue, packages/radix-vue/src/Toast/ToastProvider.vue, packages/radix-vue/src/Tooltip/TooltipProvider.vue
Fixes https://github.com/unovue/radix-vue/issues/1320
=> fix: set inheritAttrs to false for components that render fragments

docs/.vitepress/components/DocTopbar.vue
Fixes https://github.com/unovue/radix-vue/issues/1350
=> fix(doc): incorrectly highlight

packages/radix-vue/src/Listbox/ListboxFilter.vue
=> fix(ListboxFilter): navigate left/right within input

docs/content/guides/dates.md
=> fix(docs): update usage of parseStringToDateValue

docs/content/docs/components/tags-input.md, packages/core/src/TagsInput/TagsInput.test.ts, packages/core/src/TagsInput/TagsInputInput.vue, packages/core/src/TagsInput/TagsInputRoot.vue
Cherry-picked from https://github.com/unovue/radix-vue/pull/1408 ! 🙈
=> feat(TagsInput): support multiple delimiters via RegExp

docs/components/demo/Combobox/tailwind/index.vue, packages/radix-vue/src/Combobox/ComboboxInput.vue, packages/radix-vue/src/Combobox/ComboboxRoot.vue
This PR will fix #1430
I confirmed this PR will not affect English.
https://github.com/user-attachments/assets/2d0c7da6-6433-4167-a706-74789ea59db8
and will fix problem that is specific to languages that has conversion concept.
https://github.com/user-attachments/assets/19b8c48a-4d2c-446b-910a-f97762ebf6f1
I might be overlooking points that I haven't fully considered. If there's anything that stands out or seems concerning, please let me know.
=> fix(Combobox): onInputEnter handler should not be triggered when isComposing true

packages/radix-vue/src/TagsInput/TagsInputInput.vue, playground/nuxt/app.vue, playground/nuxt/tailwind.config.ts
=> fix(TagsInput): fix IME enter key issue in TagsInput

packages/radix-vue/src/RangeCalendar/useRangeCalendar.ts
=> fix(RangeCalendar): highlighted range same day calculation for max-value

packages/radix-vue/src/Select/SelectItemAlignedPosition.vue, packages/radix-vue/src/Select/SelectViewport.vue, packages/radix-vue/src/shared/clamp.ts
=> fix(Select): prevent negative starting position

packages/radix-vue/src/Presence/usePresence.ts
=> fix(Presence): ensure onAnimationEnd when closing

packages/radix-vue/src/Avatar/AvatarImage.vue, packages/radix-vue/src/Avatar/utils.ts
=> feat(Avatar): support referrer policy in `AvatarImage.vue`

docs/components/demo/CalendarSelect/css/index.vue, docs/components/demo/CalendarSelect/tailwind/index.vue, packages/radix-vue/src/Calendar/story/CalendarSelect.story.vue
I've added Iran to calendar preferences options.
=> feat(calendar-demo): :sparkles: Add Iran to preferences options

packages/radix-vue/src/TagsInput/TagsInputRoot.vue
=> fix(TagsInputRoot): avoid mutating modelValue directly

packages/core/src/DatePicker/DatePickerCellTrigger.vue
add missing parentheses to defineSlots.
=> fix(DatePicker): add missing parentheses to defineSlots

packages/radix-vue/src/DatePicker/DatePickerRoot.vue
=> fix(DatePicker): remove placeholder copy condition

packages/core/src/Dialog/utils.ts
Well, **`reka.com`** is quite expensive domain name, so reverting it back to **`reka-ui.com`**
=> chore: fix site url

packages/core/README.md
Corrected a minor typo in the [README.md](https://github.com/unovue/reka-ui/blob/v2/packages/core/README.md) file. Changed "All PRs all welcomed!" to the correct "All PRs are welcomed!" to improve grammar and clarity.
=> docs: Fix typo in README.md

docs/components/demo/CalendarSwipe/css/index.vue, docs/components/demo/CalendarSwipe/css/styles.css, docs/components/demo/CalendarSwipe/tailwind/index.vue, docs/components/demo/CalendarSwipe/tailwind/tailwind.config.js, docs/content/docs/components/calendar.md
Hi! I prepared the example how to handle swipe to change months in calendar. The solution was provided some time ago by epr3 and I hope as a good way to handle this functionality it should be described in documentation
=> docs: add calendar swipe gesture navigation example

docs/content/showcase.md
Please allow us to add [Una-UI](https://unaui.com/) to the packages section, as the framework relies heavily on reka-ui primitives. 
thanks ahead! 💛
=> docs(showcase): add `una-ui` to the packages section

packages/core/src/Combobox/ComboboxItem.vue
`provideComboboxItemContext` was never called.
=> fix(Combobox): call provideComboboxItemContext

packages/core/src/Calendar/Calendar.test.ts, packages/core/src/Calendar/CalendarCellTrigger.vue, packages/core/src/Calendar/story/_Calendar.vue, packages/core/src/RangeCalendar/RangeCalendarCellTrigger.vue
=> fix(Calendar): properly calculate focus for next month when pagedNavigation is false

packages/core/src/shared/useGraceArea.ts
=> fix: catching target not existing for grace area

docs/content/meta/DateRangePickerRoot.md, docs/content/meta/RangeCalendarRoot.md, packages/core/src/Calendar/useCalendar.ts, packages/core/src/DateRangePicker/DateRangePickerCalendar.vue, packages/core/src/DateRangePicker/DateRangePickerRoot.vue, packages/core/src/RangeCalendar/RangeCalendarRoot.vue, packages/core/src/RangeCalendar/useRangeCalendar.ts, packages/core/src/date/comparators.ts
Feature already discussed in: [#1794](https://github.com/unovue/reka-ui/pull/1794) with @epr3.
=> feat(DateRangePicker/RangeCalendar): add `isDateHighlightable` property

docs/content/meta/RovingFocusItem.md, packages/core/src/RovingFocus/RovingFocusItem.vue
Fix failing typo check: https://github.com/unovue/reka-ui/actions/runs/14519918144/job/40738081412?pr=1832
=> chore(roving-focus-item): fix typos

packages/core/src/Tooltip/TooltipTrigger.vue
=> fix(tooltip): close tooltip on pointer down when open
