- packages/radix-vue/src/DropdownMenu/DropdownMenuSeparator.vue
- packages/radix-vue/src/Separator/Separator.vue
- packages/radix-vue/src/Toolbar/ToolbarSeparator.vue
- packages/radix-vue/src/shared/component/BaseSeparator.vue
create BaseSeparator in shared
#20 #27 #9
> dev: refactor separator components, create BaseSeparator

- packages/radix-vue/src/Collapsible/CollapsibleRoot.vue
- packages/radix-vue/src/HoverCard/HoverCardContent.vue
- packages/radix-vue/src/HoverCard/HoverCardRoot.vue
- packages/radix-vue/src/HoverCard/HoverCardTrigger.vue
- packages/radix-vue/src/Popover/PopoverClose.vue
- packages/radix-vue/src/Popover/PopoverContent.vue
- packages/radix-vue/src/Popover/PopoverRoot.vue
- packages/radix-vue/src/Popover/PopoverTrigger.vue
- packages/radix-vue/src/Switch/SwitchRoot.vue
- packages/radix-vue/src/Switch/SwitchThumb.vue
- packages/radix-vue/src/Toggle/Toggle.vue
- packages/radix-vue/src/Tooltip/TooltipContent.vue
- packages/radix-vue/src/Tooltip/TooltipRoot.vue
- packages/radix-vue/src/Tooltip/TooltipTrigger.vue
- playground/vue3/src/components/Demo/AlertDialogDemo.vue
- playground/vue3/src/components/Demo/CheckboxDemo.vue
- playground/vue3/src/components/Demo/CollapsibleDemo.vue
- playground/vue3/src/components/Demo/DialogDemo.vue
- playground/vue3/src/components/Demo/DropdownMenuDemo.vue
- playground/vue3/src/components/Demo/HoverCardDemo.vue
- playground/vue3/src/components/Demo/PopoverDemo.vue
- playground/vue3/src/components/Demo/SwitchDemo.vue
- playground/vue3/src/components/Demo/TabsDemo.vue
- playground/vue3/src/components/Demo/ToggleDemo.vue
- playground/vue3/src/components/Demo/TooltipDemo.vue
- pnpm-lock.yaml
Enable components to be controlled or uncontrolled, functioning either by providing state via v-model or without.
Make the state reactive via v-model input and able to work on its own without needing to provide state.
Some components shouldnt need to be provided state manually to work, e.g. collapsible or popover. Some others needs to be handled via outside function that mutates the v-model binded, a 2-way binding must work perfectly.
In demo page we will add a custom button that mutates the v-model input to the components. Other than that, we will try and remove v-model to see if it works without it.
> fix: enable components to be controlled or uncontrolled

- packages/radix-vue/src/Tabs/TabsRoot.vue
- playground/vue3/src/components/Demo/TabsDemo.vue
Remove dependencies on v-model. So tabs should now be working without v-model, as it will have it's own local state now.
> feat: allow defaultValue props, able to work without v-model

- packages/radix-vue/src/Primitive/Primitive.vue
- playground/vue3/src/components/Demo/AccordionDemo.vue
because `AccordionTrigger` is wrapped with `CollapsibleTrigger`, somehow that makes the `asChild` doesn't work.
this would closed off #129  as well, as we are not passing `slots.default?.()` now
> fix: primitive `aschild` not working properly

- packages/radix-vue/src/NavigationMenu/NavigationMenuViewport.vue
Remove `setRef` causing the rendering recursive issue
> fix: NavigationMenu recursive issue causing crash

- packages/radix-vue/src/AlertDialog/AlertDialogRoot.vue
- packages/radix-vue/src/Dialog/DialogRoot.vue
- packages/radix-vue/src/Menubar/MenubarRoot.vue
The following warning will appear when the `key` of `useVModel`'s parameters is not defined in `defineEmits`.
```console
[Vue warn]: Component emitted event "xxxx" but it is neither declared in the emits option nor as an "xxxx" prop.
```
1. update the event name in `defineEmits` to the same as the `key` of `useVModel`'s parameters. `AlertDialogRoot`,`DialogRoot`
2. remove redundant event names. `MenubarRoot`
- #252 
make a better DX
Tested it with histoire.
> fix: component emitted an undefined event.

- packages/radix-vue/src/Tooltip/TooltipTrigger.vue
Removes unnecessary inline style (cursor: default) in TooltipTrigger
#258
Prevents cursor styles from child elements from being overridden
> fix(tooltip): Remove unnecessary inline style

- packages/radix-vue/src/Accordion/AccordionItem.vue
- packages/radix-vue/src/shared/useSingleOrMultipleValue.ts
Rather that activating always the single element, we toggle the element `on` and `off`
> [useSingleOrMultiple] fix: Toogle value

- packages/radix-vue/src/AlertDialog/AlertDialogContent.vue
- packages/radix-vue/src/AlertDialog/AlertDialogRoot.vue
- packages/radix-vue/src/Dialog/DialogContent.vue
- packages/radix-vue/src/Dialog/DialogRoot.vue
**The dialog has some wrong behaviors. Include `Dialog` and `AlertDialog`**
- Always scrollable background on mobile browser.
- Can't scroll the dialog content by mouse wheel, when its overflow behavior is scroll.
1. Remove `wheel` event listener. 
If the `DialogContent` is a scrollable componet, `wheel` prevented will make content can't scroll by mouse wheel.
2. Lock body scroll
Through `useScrollLock`, easy to lock body scrolling on mobile and Desktop. It adds style: `overflow: hidden` to body.
- #256
Fixed an issue 
- #256
Yes, tested with histoire. Include mobile and desktop.
https://github.com/radix-vue/radix-vue/assets/37807381/baa92df9-e5b2-40c8-93d1-6d7c22486466
https://github.com/radix-vue/radix-vue/assets/37807381/382e1911-58f8-4427-9fae-075a88510e36
> [Dialog]: fix the screen scrolling behavior

- packages/radix-vue/src/ScrollArea/ScrollAreaViewport.vue
Turns out using inline styling doesn't causes some weird bug of not scrolling. Moved back to use Vue SFC's style tag
> [Bug]: ScrollArea unable to scroll

- packages/radix-vue/env.d.ts
I encountered that the histoire components were not being detected by typscript. I fixed this according to the histoire documentation.
https://histoire.dev/guide/vue3/getting-started.html#typescript
> BEFORE
> AFTER
> chore: add types for histoire components

- packages/radix-nuxt/src/index.ts
This PR allows for (optionally) prefixing auto-imported Nuxt components' names.
> feat: add `prefix` option to Nuxt module

- docs/components/demo/NavigationMenu/tailwind.config.js
Adding a teal color to Tailwind file for NavigationMenu docs since it's missing in the documentation.
> docs: tailwind file for NavigationMenu docs file

- README.md
- docs/components/tables/EmitsTable.vue
- docs/components/tables/PropsTable.vue
I was browsing the docs in a bright environment with light mode turned on and noticed the popovers weren't readable. In this small contribution colors in light mode are fixed. I've also updated the positioning of the popover trigger in the `EmitsTable` to match the `PropsTable`.
> docs:  tables info popover styles

- docs/components/Tooltip.vue
- docs/components/demo/Tooltip/index.vue
- docs/components/home/demos/TooltipDemo.vue
- packages/radix-vue/src/Tooltip/stories/Tooltip.content.story.vue
- packages/radix-vue/src/Tooltip/stories/Tooltip.story.vue
- packages/radix-vue/src/Tooltip/stories/_Tooltip.vue
- playground/nuxt/components/TooltipDemo.vue
- playground/vue3/src/components/Demo/TooltipDemo.vue
As we chat in Discord, we will recomend the use of `Teleport`.
Therefore, I just updated the demos for Tooltips
> chore: update Tooltip to use Portal instead of Teleport

- packages/radix-vue/src/Avatar/Avatar.test.ts
- packages/radix-vue/src/Avatar/AvatarFallback.vue
- packages/radix-vue/src/Avatar/AvatarImage.vue
- packages/radix-vue/src/Avatar/story/Avatar.story.vue
- packages/radix-vue/src/Avatar/utils.ts
There is a list of users, and you want to select one from the list. When a user is selected, we display the selected user's avatar.
1. We select A user, and A user has no avatar, it will show the Fallback avatar.
2. Then select B user, and B user has avatar, without reactive, it will still show the Fallback avatar.
> fix: allow AvatarImage to be reactive

- packages/radix-vue/src/Dialog/DialogOverlay.vue
Fixes #455 
Also tested in Nuxt (SSR), works fine.
> fix: lock body scroll on initial render

- docs/content/guides/styling.md
Just stumbled on this small syntax error.
I also noticed, that you currently cannot get typed emits when you extend a component.
When you add them like this
```html
<template>
<AccordionItem v-bind="$props"><slot /></AccordionItem>
</template>
<script lang="ts" setup>
import { AccordionItem, type AccordionItemProps, type AccordionItemEmits } from "radix-vue";
defineProps<AccordionItemProps>()
defineEmits<AccordionItemEmits>()
</script>
```
then the typescript works, but they are never getting emitted/called. I also tried to add them like `<AccordionItem v-bind="{  ...$props, ...$attrs }"><slot /></AccordionItem>`, same story.
> docs: update extending example

- packages/radix-vue/src/Popper/PopperArrow.vue
In the `PopperArrow` component, the `width` and `height` properties aren't being passed to the `Arrow` component. Despite providing values for `width` and `height`, they always default to `width="10"` and `height="5"`.
ref. Docs for `PopoverArrow` https://www.radix-vue.com/components/popover.html#arrow
> [PopperArrow] `width` and `height` aren't passed to `Arrow`

- packages/radix-vue/src/Popover/story/PopoverCustomArrow.story.vue
- packages/radix-vue/src/Popper/PopperArrow.vue
`asChild` in `Popover` component didn't work because `slot` wasn't used in `PopperArrow` component.
> fix(PopoverArrow): make asChild work as expected

- docs/content/components/dialog.md
- packages/radix-vue/src/Dialog/DialogClose.vue
To be in line with Radix UI. Authors can still set `aria-label="Close"` themselves, or use another method to provide an accessible name.
Resolves #541
> fix(Dialog): remove `aria-label="Close"` from DialogClose

- packages/radix-vue/src/PinInput/PinInputInput.vue
Resolves #549.
Addresses the direct mutation of `modelValue` elements in `PinInputInput`s by using a temporary copy.
This workaround seems a little clunky, but currently, I couldn't think of a better solution. Feedback is appreciated!
> fix(PinInput): modelValue elements mutated directly

- docs/.vitepress/config.ts
The current `theme-color` simply doesn't match the logo and og:image color scheme.
> chore: change docs theme-color 

- docs/content/components/slider.md
`v` is of type `number[] | undefined`:
> Update slider.md: correct parameter type

- packages/radix-vue/src/Menu/MenuItemImpl.vue
resolves: #600
Original radix-ui doesn't set disabled attribute to MenuItem component. Only `aria-disabled` and `data-disabled` https://github.com/radix-ui/primitives/blob/c31c97274ff357aea99afe6c01c1c8c58b6356e0/packages/react/menu/src/Menu.tsx#L708-L709
If you want to use MenuItem as button - use `asChild` props 
```vue
<MenuItem as-child disabled>
<button disabled>
Hello world
</button>
</MenuItem>
```
> fix: don't set disabled attribute to `MenuItem` component

- packages/radix-vue/src/Tabs/TabsIndicator.vue
Fixes the issue where the tab indicator doesn't update its position when the container changes size. #602
> fix(TabsIndicator): add ResizeObserver (#602)

- packages/radix-vue/src/Combobox/ComboboxContentImpl.vue
- packages/radix-vue/src/Select/SelectContent.vue
- packages/radix-vue/src/Select/SelectContentImpl.vue
Related PR in `shadcn-vue`
https://github.com/radix-vue/shadcn-vue/pull/272
---
`PopperContent.vue` already has [`avoidCollisions: true` prop by default](https://github.com/radix-vue/radix-vue/blob/main/packages/radix-vue/src/Popper/PopperContent.vue#L20), in other **Primitive Wrappers** (SelectContentImpl.vue) 
We pass down the same `PopperContent` types props but Vue will cast boolean props as false which will override the **Main Primitive** (PopperContent.vue) prop value
Now I fully understand why you create `useForwardProps`
- [React Playground](https://stackblitz.com/edit/vitejs-vite-fzy92e?file=src%2FApp.tsx,src%2Fmain.tsx,src%2Fcomponents%2FAnotherPrimitive.tsx,src%2Fcomponents%2FPrimitives.tsx&terminal=dev)
- [Vue SFC Playground](https://play.vuejs.org/#eNqVVl1P2zAU/StWHgZINIHB9tAV …
> fix: prevent override default boolean prop value with useForwardProps

- docs/content/components/toast.md
- Module '"vue"' has no exported member 'InstanceType'.
- `InstanceType` is in `typescript`
```ts
/**
* Obtain the return type of a constructor function type
*/
type InstanceType<T extends abstract new (...args: any) => any> = T extends abstract new (...args: any) => infer R ? R : any;
```
> docs: update toast.md

- packages/radix-vue/src/Toggle/ToggleRoot.vue
This PR is related to #638.
I saw `ToggleRoot` emitted an event twice, `@click` and `@keydown.enter`. This made `pressed` was mutated twice too.
Then, I removed `@keydown.enter`, an event was still emitted after pressing `Enter` but only once from `@click`.
`@click` works with pressing `Space` too.
I have removed `@keydown.enter` from `ToggleRoot`.
-------
If you have any feedback or suggestion, please let me know.
> fix: remove duplicate keydown enter

- packages/radix-vue/src/Pagination/PaginationRoot.vue
I had to style the pagination items based on, among other things, total number of pages, and found out that it's not exposed by radix-vue. While it's not a big deal and can be computed easily regardless, I figured it would be a nice little addition to expose an already computed value on `PaginationRoot` component.
I also noticed that there's no component or any convention on how document scoped slots props in the docs (probably due to the fact the slots are rarely used in this library). I improvised a little bit and decided to use `PropsTable` to describe scoped slots props for `PaginationRoot` as well as `PaginationList`.
Furthermore, I'm also not sure whether I should write test(s) for this (and what such tests should look like). I was looking in `@vue/test-utils` docs to find a way to …
> feat(Pagination): expose page count on PaginationRoot

- docs/content/guides/styling.md
#651
This adds a note about scoped styles, and the need to use deep selectors when styling teleported elements.
> docs: add notes about scoped styles

- docs/components/demo/Avatar/css/index.vue
In  the docs https://www.radix-vue.com/components/avatar.html
style should be `:style="{ display: 'flex', gap: '20px' }`
not `:style="{ display: 'flex', gap: 20}`
> docs: fix demo Avatar styles

- packages/radix-vue/src/Combobox/ComboboxRoot.vue
Please first read this issue: https://github.com/radix-vue/shadcn-vue/issues/327
So I delved deeper inside `radix-vue` codebase and searched that `type AcceptableValue = string | number | boolean | object`
But `object` type inside TS is more that just object we think about:
```typescript
let obj: object;
obj = {}; // Allowed
obj = []; // Allowed
obj = () => {}; // Allowed
obj = 42; // Not allowed, because 42 is a primitive type
```
type `Object` don't feet too I think:
```typescript
let obj: Object;
obj = {}; // Allowed
obj = []; // Allowed
obj = new Object(); // Allowed
obj = () => {}; // Not allowed, because () => {} is not an instance of Object
```
So I think that the best `object` for this values will be `PlainObject`:
```typescript
type PlainObject = Record<string, any>;
```
So, this …
> fix(Combobox): update `AcceptableValue` inside `Combobox.vue`

- packages/radix-vue/src/Checkbox/index.ts
Makes it more convenient to provide type information for e.g. `ref` or `computed`:
```
import type { CheckboxCheckedState } from 'radix-vue'
const isChecked = ref<CheckboxCheckedState>(false)
```
> chore(Checkbox): export `CheckboxCheckedState` type

- packages/radix-vue/src/Checkbox/Checkbox.test.ts
- packages/radix-vue/src/Checkbox/CheckboxRoot.vue
When checkbox is in indeterminate state, we should account for it in the click handler and set the state to `true`.
Reference:
https://github.com/radix-ui/primitives/blob/c31c97274ff357aea99afe6c01c1c8c58b6356e0/packages/react/checkbox/src/Checkbox.tsx#L93C42-L93C57
> fix(Checkbox): check indeterminate state in click event handler

- packages/radix-vue/src/Select/SelectTrigger.vue
Related issue https://github.com/radix-vue/shadcn-vue/issues/354
https://stackblitz.com/edit/xyl3we?file=src%2FApp.vue
I think we need to `check/cleanup` all components from up to bottom from radix-ui
> fix: `SelectTrigger` is not disabled when passing disabled prop to `SelectRoot`

- docs/content/components/dialog.md
- packages/radix-vue/src/DismissableLayer/utils.ts
It seems that my last change in #695 did not fix the problem completely. After upgrading to the latest version, one of my Select components now works, but the other does not. And some of the dropdowns are not working as expected.
```ts
if (event.clientX > target.clientWidth || event.clientY > target.clientHeight)
return
```
As I undrestand it, we need those lines for this particular example of dialog: https://www.shadcn-vue.com/docs/components/dialog.html#scroll-overlay. To handle the case when we click on the scrollbar and the dialog closes. This is valid issue, but I think this is the wrong way to fix it. We dont need to modify the composable, because it will affect all other components and break a lot of things. We can modify the `@pointer-down-outside` handler just for this case with …
> fix: remove coords check in `usePointerDownOutside`

- packages/radix-vue/src/DismissableLayer/utils.ts
I'm working on another reactivity refactor [here](https://github.com/vuejs/core/tree/reactivity-refactor) and noticed uncaught errors in radix-vue tests (despite all the tests passing): https://github.com/vuejs/ecosystem-ci/actions/runs/8029583738/job/21936045284
The root cause here is that the refactor gives computed a more correct behavior in that it will always give the latest value, even if its owner component has unmounted.
Previously, computed's effect is stopped after the owner component is unmounted, causing it to become stale and always return the last value before unmount. The refactor removed the need to "stop" a computed, and ensures that it never gets stale even when it has no subscriber.
The line in question here happens to rely on this behavior: although it checked for …
> Handle possible null element in useFocusOutside focus callback

- docs/content/meta/ComboboxRoot.md
- packages/radix-vue/src/Combobox/ComboboxRoot.vue
Resolves #698 
This is a simple PR that improves the type of `ComboboxRootProps`. Since the `ComboboxRoot` component allows `multiple` to select more than one value, the `modelValue` and `defaultValue` can also be an array.
> fix(Combobox): Allow array type for `modelValue` and `defaultValue`

- packages/radix-vue/src/Combobox/ComboboxRoot.vue
Resolves #708 
This PR aims to remove the warning caused when opening the `ComboboxContent`, which says the following:
```
[Vue warn] Computed is still dirty after getter evaluation, likely because a computed is mutating its own dependency in its getter. State mutations in computed getters should be avoided.
```
This warning seems to occur at the `ComboboxRoot` component when reading the value of the `options` property inside of a regular `computed`. The `options` property uses the VueUse utility `computedWithControl` to only change the value when `itemMapSize` changes. 
However, as mentioned in the following issue from VueUse (https://github.com/vueuse/vueuse/issues/3794#issuecomment-1951369704) it is recommended to instead use a `watch` to perform the side effects, instead of …
> fix(Combobox): Computed warning when opening items

- package.json
- pnpm-lock.yaml
Fresh installs prompt to download old version (8.9.2) only for the package-lock to be at recent version (8.15.3).
> chore(deps): bump pnpm to 8.15.4

- packages/radix-vue/src/ToggleGroup/ToggleGroup.test.ts
- packages/radix-vue/src/ToggleGroup/ToggleGroupItem.vue
- packages/radix-vue/src/ToggleGroup/story/_ToggleGroup.vue
- packages/radix-vue/src/shared/useSingleOrMultipleValue.ts
resolves #754
But another problem remains. providing a default value in `useSingleOrMultipleValue` for `modelValue` never let's the model to be undefined in `single` mode. so in that mode, we can never uncheck all `toggle` items.
I really don't know if this is intentional or not. 
Try to comment line `74` of `useSingleOrMultipleValue.ts` file and then try to uncheck all toggle values in the reproduction provided in #754
> fix: making toggle pressed  logic a computed property

- docs/content/utilities/use-forward-props-emits.md
This PR fixes a the wrong TS types in the `useForwardPropsEmits` docs example
> chore: useForwardPropsEmits doc fix

- packages/radix-vue/src/Select/SelectContent.vue
- packages/radix-vue/src/Select/story/SelectDemo.story.vue
Hi 👋🏻 Closes #787 
- rewrite template for using v-if/ v-else
- wrap select provider in `div`
It's bug because `<Transiton />` can't be applied on fragment or multi root components. I tried some hacks and debug, and come up with this solution:
- set prop `present` in `Presence` component to `true`. And move old prop value to `v-if`
- wrap `Teleport` with `div` and `v-else-if` condition.
And it works. Maybe I'm missing something, but it works  😅
https://github.com/radix-vue/radix-vue/assets/20302368/fb77015e-9cca-446a-9409-34ffdd5b3403
> fix(select): fix select content animation

- docs/package.json
- docs/scripts/update-contributors.ts
- pnpm-lock.yaml
- `ohmyfethc` is deprecated package and it is used only once in codebase. There is no real reason why we can't use just `fetch`
- `esno` is currently just an alias for `tsx`, so I mean.. why to install one more package
> chore(docs): remove `ohmyfetch` dependency and use `tsx` instead of `esno`

- .histoire/package.json
- .histoire/tailwind.config.js
- packages/radix-vue/src/DropdownMenu/story/DropdownMenu.story.vue
- packages/radix-vue/src/Primitive/Slot.ts
- pnpm-lock.yaml
resolves: #800 
The main change that brought the out transition back was:
```ts
if (childrens.length === 1)
return cloned
```
Basically unwrap the vnodes array if it only has one element. Idk why this is fixed, but it works XD. I'd like others to look at this, because I'm not really sure about it. 
I should probably write a story to showcase this, but I'm lazy right now. I'll get back to it tomorrow.
> fix: slot prevents out transition for non-modal dropdown and select components

- packages/radix-vue/src/shared/date/calendar.ts
Hello,
This PR fixes an issue outlined by @sadeghbarati in which the `createDecade` doesn't output the correct year progression, but it just jumps from the current year to 10 years in the future.
Screenshot of the issue on `CalendarPopover.story.vue`:
> fix(date): shared calendar year jump on createDecade

- packages/radix-vue/src/RangeCalendar/RangeCalendar.test.ts
- packages/radix-vue/src/RangeCalendar/useRangeCalendar.ts
Bug and image provided by @sadeghbarati 
`data-selection-start=true` wasn't being applied when you were first selecting a value in the range, it was being applied only when you selected both dates of the range.
> fix(RangeCalendar): data-selection-start not being applied on first select

- packages/radix-vue/src/HoverCard/HoverCardTrigger.vue
- packages/radix-vue/src/HoverCard/utils.ts
Let's just remove this.
In Radix Primitives for React this doesn't even do anything as the `event` there is some weird React abstraction.
> fix: make hover card tappable

- docs/content/components/hover-card.md
This PR simply adds the missing Keyboard Interactions to the Hover Card docs.
Currently they say that it does not respond to keyboard interactions, but in reality it does to `Enter` and `Tab`.
The interactions where taken from Radix UI's docs on the Hover Card.
> docs(HoverCard): Add missing keyboard interactions

- docs/components/Tooltip.vue
- docs/components/demo/HoverCard/css/index.vue
- docs/components/demo/HoverCard/tailwind/index.vue
- docs/components/demo/Tooltip/css/index.vue
- docs/components/demo/Tooltip/tailwind/index.vue
- packages/radix-vue/src/HoverCard/story/_HoverCard.vue
Looks like the `size` (string) prop should actually be `width` (number) in examples according to the docs.
Thanks for this excellent library!
> Fix size prop should be width (number)

- packages/radix-vue/src/Select/Select.test.ts
- packages/radix-vue/src/Select/SelectContentImpl.vue
- packages/radix-vue/src/Select/SelectItem.vue
- packages/radix-vue/src/Select/SelectTrigger.vue
This PR aims to improve the behavior of the `Select` component on touch devices.
Fixes: #804 
On the latest version of Radix UI (v1.6.1) if you try to scroll on a touch screen device and the initial tap to begin the scroll gesture fell on the `SelectTrigger`, it prevents scrolling and immediately opens the `SelectContent`.
This behavior feels wrong to the end user because they expect to be able to scroll by tapping anywhere on the screen. But if they tap on any `SelectTrigger`, not only does it lock scrolling, it also opens the `SelectContent` and feels like a bug.
See #804 for more details.
The issue was caused by the `SelectTrigger` opening the `SelectContent` via the `@pointerdown` event, which feels normal with a mouse, but on touch devices it gets triggered immediately after touching …
> fix(Select): Touch scroll triggers the select content

- packages/radix-vue/src/Calendar/CalendarRoot.vue
- packages/radix-vue/src/Calendar/story/CalendarDefault.story.vue
- packages/radix-vue/src/Calendar/useCalendar.ts
- packages/radix-vue/src/RangeCalendar/RangeCalendarRoot.vue
Hello,
This PR fixes an issue with the `Calendar/RangeCalendar` always updating the grid view (with the `numberOfMonths` prop set to a number greater than 1) when selecting a date on a month other than the first in the grid view, even if the date is part of the `visibleView`.
EDIT: This PR also makes all props inside `useCalendar` reactive and adds a watcher to update the `CalendarGrid` on props update.
cc @sadeghbarati for reporting this 🚀
> fix(useCalendar): grid update condition in watcher

- docs/content/meta/CalendarRoot.md
- docs/content/meta/DateFieldRoot.md
- docs/content/meta/DatePickerRoot.md
- docs/content/meta/DateRangeFieldRoot.md
- docs/content/meta/DateRangePickerRoot.md
- docs/content/meta/RangeCalendarRoot.md
- packages/radix-vue/src/Calendar/CalendarCellTrigger.vue
- packages/radix-vue/src/Calendar/CalendarRoot.vue
- packages/radix-vue/src/Calendar/story/CalendarDir.story.vue
- packages/radix-vue/src/DateField/DateFieldRoot.vue
- packages/radix-vue/src/DatePicker/DatePickerCalendar.vue
- packages/radix-vue/src/DatePicker/DatePickerField.vue
- packages/radix-vue/src/DatePicker/DatePickerRoot.vue
- packages/radix-vue/src/DateRangeField/DateRangeFieldRoot.vue
- packages/radix-vue/src/DateRangePicker/DateRangePickerCalendar.vue
- packages/radix-vue/src/DateRangePicker/DateRangePickerField.vue
- packages/radix-vue/src/DateRangePicker/DateRangePickerRoot.vue
- packages/radix-vue/src/RangeCalendar/RangeCalendarCellTrigger.vue
- packages/radix-vue/src/RangeCalendar/RangeCalendarRoot.vue
This feature adds support for the `dir` property for all date-related components from `ConfigProvider` or from the HTML tags.
Also added a story in `Calendar` for showcase.
cc @sadeghbarati for the PR and for suggesting the feature
> feat: add direction support for Calendar/Date Field/Date Picker 

- docs/content/meta/TabsContent.md
- docs/content/meta/TabsRoot.md
- docs/content/meta/TabsTrigger.md
- packages/radix-vue/src/Tabs/Tabs.test.ts
- packages/radix-vue/src/Tabs/TabsContent.vue
- packages/radix-vue/src/Tabs/TabsRoot.vue
- packages/radix-vue/src/Tabs/TabsTrigger.vue
- packages/radix-vue/src/Tabs/story/_Tabs.vue
- packages/radix-vue/src/Tabs/utils.ts
- packages/radix-vue/src/shared/types.ts
Hi! 👋🏻 Closes #820 
- `TabsTrigger`, `TabsRoot`, `TabsContent` components now accept `string` or `number` values
- `defaultValue` in `TabsRoot` component now accept `string` or `number` values
- utils function for generating contentId and triggerId now accept value as `string` or `number`
- create type `StringOrNumber` in `shared/types`.
- update testing component template for using numbers and strings. All tests passed
- gen docs
> feat(tabs): tabs components accepts string or number values

- packages/radix-vue/src/Calendar/CalendarRoot.vue
- packages/radix-vue/src/RangeCalendar/RangeCalendarRoot.vue
- packages/radix-vue/src/date/calendar.ts
This PR aligns the `createYear` and `createDecade` utilities to be consistent in generating the months of the year/years of a range with the `createMonths` function, thus removing the need of passing through the `minValue`/`maxValue`.
It also fixes issues with the functions returning an empty array when the `minValue` and/or `maxValue` props were provided.
cc @sadeghbarati
> Refactor: remove minValue and maxValue from calendar utilities

- docs/content/guides/dates.md
- docs/content/meta/CalendarRoot.md
- docs/content/meta/DatePickerCalendar.md
- docs/content/meta/DateRangePickerCalendar.md
- docs/content/meta/RangeCalendarRoot.md
- packages/radix-vue/src/Calendar/CalendarRoot.vue
- packages/radix-vue/src/Calendar/story/CalendarPopover.story.vue
- packages/radix-vue/src/DatePicker/DatePickerCalendar.vue
- packages/radix-vue/src/DateRangePicker/DateRangePickerCalendar.vue
- packages/radix-vue/src/RangeCalendar/RangeCalendarRoot.vue
- packages/radix-vue/src/RangeCalendar/story/RangeCalendarPopover.story.vue
- packages/radix-vue/src/date/calendar.ts
Hello,
This PR removes redundant slot prop functions from the `Calendar` components which are now exposed through `radix-vue/date` and `useDateFormatter` respectively, namely `getYears`, `getMonths` and `formatter`, plus some minor fixes to the code and stories which were using the slot props.
Also, it adds a new function to `radix-vue/date`: `createYearRange` which returns a year range between a `start` year and a `end` year.
cc @sadeghbarati for the `createYearRange` function suggestion
> feat: create year range

- docs/content/guides/server-side-rendering.md
Thanks for supporting custom `useId` implementation ! It seems it went under my radar.
Since this is an SSR issue, I've added some information on SSR page from `ConfigProvider` section.
> docs: reference hydration section in SSR page

- docs/content/meta/CalendarRoot.md
- docs/content/meta/DatePickerCalendar.md
- docs/content/meta/DateRangePickerCalendar.md
- docs/content/meta/RangeCalendarRoot.md
- packages/radix-vue/src/Calendar/CalendarRoot.vue
- packages/radix-vue/src/DatePicker/DatePickerCalendar.vue
- packages/radix-vue/src/DateRangePicker/DateRangePickerCalendar.vue
- packages/radix-vue/src/RangeCalendar/RangeCalendarRoot.vue
Hello,
This PR exposes the `fixedWeeks`, `weekStartsOn` and `locale` props through the `CalendarRoot`/`RangeCalendarRoot` slot props, mainly for usage with the methods in `radix-vue/date` to handle the case when you would want to use the utility functions in an uncontrolled component (by providing the props just in the `template`), so that you don't have to lift the state up in a `ref`).
> feat: calendar slot export

- docs/.vitepress/theme/style.css
While reading the documentation, I noticed that in light mode, the color of links in the TIP blocks maintains the value of the dark theme. 
This PR sets a more legible color for those links. I selected `--vp-c-brand-darker`, the darker out of the brand colors, because I think the one used elsewhere (`--vp-c-brand-1`) doesn't have enough contrast on the block's background. 
**Before**
**After**
> Docs: fix link color in tip blocks on light theme

- packages/radix-vue/src/Calendar/useCalendar.ts
This PR fixes an issue with the `Calendar` and `RangeCalendar` not updating the grid if `number-of-months` was larger than 1.
Kudos to @JustinBordage for finding this issue in `shadcn` and providing a fix: https://github.com/radix-vue/shadcn-vue/issues/500.
Should fix downstream issue in `shadcn`.
cc @sadeghbarati
> fix(useCalendar): fix grid not working on prev page

- docs/components/demo/DateField/tailwind/index.vue
- docs/components/demo/DatePicker/tailwind/index.vue
- docs/components/demo/DateRangeField/tailwind/index.vue
- docs/components/demo/DateRangePicker/tailwind/index.vue
- docs/content/components/date-field.md
- docs/content/components/date-picker.md
- docs/content/components/date-range-field.md
- docs/content/components/date-range-picker.md
- packages/radix-vue/src/DateField/story/DateFieldChromatic.story.vue
- packages/radix-vue/src/DateField/story/DateFieldDefault.story.vue
- packages/radix-vue/src/DateField/story/DateFieldGranular.story.vue
- packages/radix-vue/src/DateField/story/DateFieldInvalid.story.vue
- packages/radix-vue/src/DateField/story/DateFieldLocales.story.vue
- packages/radix-vue/src/DateField/useDateField.ts
- packages/radix-vue/src/DatePicker/story/DatePickerDefault.story.vue
- packages/radix-vue/src/DatePicker/story/_DummyDatePicker.vue
- packages/radix-vue/src/DateRangeField/story/DateRangeFieldDefault.story.vue
- packages/radix-vue/src/DateRangeField/story/_DummyDateRangeField.vue
- packages/radix-vue/src/DateRangePicker/story/DateRangePickerDefault.story.vue
- packages/radix-vue/src/DateRangePicker/story/_DummyDateRangePicker.vue
Closes #858.
Hello,
This PR adds the `data-placeholder` attribute to the `DateFieldInput` type components. It's enabled whenever the input is empty.
> Feat: date field placeholder data attribute

- packages/radix-vue/src/Pagination/Pagination.test.ts
- packages/radix-vue/src/Pagination/PaginationRoot.vue
this PR to fix Pagination component abnormal behaviours when total is 0:
1. `PaginationList` items is [] when total is 0
2. `PaginationNext` is clickable when total is 0
> fix(pagination): set pageCount minimal value is 1

- docs/components/demo/NavigationMenu/tailwind/index.vue
- packages/radix-vue/src/NavigationMenu/story/NavigationMenuBasic.story.vue
- packages/radix-vue/src/NavigationMenu/story/NavigationMenuDemo.story.vue
- packages/radix-vue/src/NavigationMenu/story/NavigationMenuSubmenus.story.vue
- packages/radix-vue/src/NavigationMenu/story/NavigationMenuViewport.story.vue
Currently `duration-[250]` generates `duration: 250` which does not have any effect
> chore: use correct duration class

- docs/components/demo/Tabs/tailwind/index.vue
- docs/content/meta/TabsRoot.md
- packages/radix-vue/src/Tabs/TabsRoot.vue
Adds explanation for `activationMode` prop on `TabsRoot`.
Adds outline shadow on `TabsTrigger` focus for Tabs demo. I removed the animation on `TabsIndicator` because it doesn't make sense with the shadow.
> docs: improve Tabs docs

- package.json
- packages/plugins/package.json
- pnpm-lock.yaml
I cloned a repository and then ran `pnpm install` followed by `pnpm build`. However, the build failed because it was attempting to build radix-vue and plugins in parallel, even though plugins depends on radix-vue. To fix this, I modified the build command to process the packages sequentially and changed how plugins package references radix-vue from a file protocol to a link protocol.
**Environment**
Developement/Production OS: macOS
Node version: 20.4.0
Package manager: pnpm@8.15.2
Radix Vue version: 1.7.0
**Error Output**
```
Scope: 4 of 5 workspace projects
packages/radix-vue build$ pnpm type-check && pnpm build-only
[6 lines collapsed]
│ ✓ 841 modules transformed.
│ rendering chunks...
│ [vite:dts] Start generate declaration files...
│ computing gzip size...
│ dist/date.js     4.59 kB …
```
> fix: made it so that the pnpm build succeeds right after cloning

- docs/components/demo/CalendarSelect/css/index.vue
- docs/components/demo/CalendarSelect/css/styles.css
- docs/components/demo/CalendarSelect/tailwind/index.vue
- docs/components/demo/CalendarSelect/tailwind/tailwind.config.js
- docs/content/components/calendar.md
- packages/radix-vue/src/Calendar/story/CalendarSelect.story.vue
- packages/radix-vue/src/Calendar/useCalendar.ts
- packages/radix-vue/src/shared/useDateFormatter.ts
Hello,
This PR extends the `useDateFormatter` function to also include the `calendar` identifier in its options, so you get the month names translated into your required `locale` and also updated the utility function to be able to accept `options`.
It also updates the `useCalendar` `headingValue` to use the `calendar` identifier when computing the `fullMonth`, `fullYear` and `fullMonthAndYear`.
Plus, the `props.placeholder` function has been updated to use `isEqualMonth` so any calendar system change would update the `grid`.
cc @sadeghbarati for pointing out the bug and providing me with reproductions.
> refactor(useCalendar): include calendar identifier when computing heading value

- docs/content/guides/namespaced-components.md
I found some typos in the [Namespaced](https://www.radix-vue.com/guides/namespaced-components.html) guide. I also reworded some paragraphs, but since English is not my native language, please take it with a grain of salt 😅 .
> docs(namespaced): fix reword and typos

- docs/content/meta/SelectContent.md
- packages/radix-vue/src/Select/SelectContentImpl.vue
Hello,
This PR adds a `bodyLock` property to the `SelectContent` component behaving in the same way as the `ComboboxContent` component.
This PR should also fix #873.
Let me know if there's anything else that would need to be added.
Thanks!
> feat(Select): body lock property

- docs/components/demo/CalendarYearIncrement/css/index.vue
- docs/components/demo/CalendarYearIncrement/css/styles.css
- docs/components/demo/CalendarYearIncrement/tailwind/index.vue
- docs/components/demo/CalendarYearIncrement/tailwind/tailwind.config.js
- docs/content/components/calendar.md
- docs/content/meta/CalendarNext.md
- docs/content/meta/CalendarPrev.md
- docs/content/meta/DatePickerNext.md
- docs/content/meta/DatePickerPrev.md
- docs/content/meta/DateRangePickerNext.md
- docs/content/meta/DateRangePickerPrev.md
- docs/content/meta/RangeCalendarNext.md
- docs/content/meta/RangeCalendarPrev.md
- packages/radix-vue/src/Calendar/Calendar.test.ts
- packages/radix-vue/src/Calendar/CalendarCellTrigger.vue
- packages/radix-vue/src/Calendar/CalendarNext.vue
- packages/radix-vue/src/Calendar/CalendarPrev.vue
- packages/radix-vue/src/Calendar/CalendarRoot.vue
- packages/radix-vue/src/Calendar/story/CalendarYearIncrement.story.vue
- packages/radix-vue/src/Calendar/story/_Calendar.vue
- packages/radix-vue/src/Calendar/useCalendar.ts
- packages/radix-vue/src/RangeCalendar/RangeCalendar.test.ts
- packages/radix-vue/src/RangeCalendar/RangeCalendarCellTrigger.vue
- packages/radix-vue/src/RangeCalendar/RangeCalendarNext.vue
- packages/radix-vue/src/RangeCalendar/RangeCalendarPrev.vue
- packages/radix-vue/src/RangeCalendar/RangeCalendarRoot.vue
- packages/radix-vue/src/RangeCalendar/story/_RangeCalendar.vue
- packages/radix-vue/src/shared/date/index.ts
- packages/radix-vue/src/shared/date/types.ts
Hello,
This PR implements a new property on the `CalendarNext`/`CalendarPrev` buttons named `step` which would be used to control how the `placeholder` is incremented/decremented (by year or by month, the last one being the default).
I believe this feature is implemented on most calendar libraries/packages and could prove useful for a lot of users.
I've also added a story and example in `Calendar` and tests for this new feature.
> feat(Calendar/RangeCalendar): step calendar increment buttons

- packages/radix-vue/src/Combobox/ComboboxRoot.vue
Fixes #843 
I have a couple other fixes that actually manages to make `ComboboxAsync.story.vue` somewhat usable. But wanted to quickly get this fix out of the way first.
> fix(ComboBox): flush option changes later

- packages/radix-vue/src/Combobox/ComboboxGroup.vue
Fixes #551 #843
After the last fix (https://github.com/radix-vue/radix-vue/pull/883) we still had a problem with a large list of grouped items (all groups were hidden by v-show).
This PR fixes the grouped lists as well.
> fix(ComboBox): nextTick for render groups

- packages/radix-vue/src/Accordion/AccordionContent.vue
In `AccordionContent` we are passing a `open` prop to the `CollapsibleContent` instance even if it does not support such prop.
On a related note: I noticed that the `data-disabled` attribute is applied even if the item or the root is not disabled. It might have something to do with the line: 
https://github.com/radix-vue/radix-vue/blob/3a4188c1afbdb7671c0e76a7e9e0253b34defa52/packages/radix-vue/src/Accordion/AccordionItem.vue#L68
but I lack the context to understand if it's a bug or not.
> Fix(accordion): remove unused open prop from the CollapsibleContent instance

- docs/components/demo/Accordion/css/index.vue
- docs/components/demo/Accordion/tailwind/index.vue
- docs/components/demo/NavigationMenu/css/index.vue
- docs/components/demo/NavigationMenu/tailwind/index.vue
- docs/content/components/accordion.md
- packages/radix-vue/src/NavigationMenu/story/NavigationMenuBasic.story.vue
- packages/radix-vue/src/NavigationMenu/story/NavigationMenuDemo.story.vue
- packages/radix-vue/src/NavigationMenu/story/NavigationMenuSubmenus.story.vue
- packages/radix-vue/src/NavigationMenu/story/NavigationMenuViewport.story.vue
This PR is not related to radix-vue itself, but to the usage of `@iconify/vue`. 
@iconify/vue already [adds `aria-hidden` by default](https://github.com/iconify/iconify/blob/59bf4012b5b66fae6b63716fac705fd275da06c2/components/vue/src/render.ts#L24), but if we set the `aria-hidden` attribute without any value, [this check](https://github.com/iconify/iconify/blob/59bf4012b5b66fae6b63716fac705fd275da06c2/components/vue/src/render.ts#L162-L167) will remove it completely, leaving a `role="img"` without name.
If this change is fine and I didn't miss anything, I can submit another to update other examples where we used the attribute on the `Icon` component.
> Docs(accordion): fix aria-hidden attribute in examples

- docs/components/DemoContainer.vue
On the home page, when a user clicks on a demo container with a title containing more than two words, they will get a 404.
For example, "Date Range Picker" generates the link: `/components/date-range%20picker.html` rather than the correct link `/components/date-range-picker.html`.
The component responsible for generating this url is `<DemoContainer>`. It uses the `title` prop to generate the link. When a title has a space, it currently substitutes a hyphen for the space using `title.replace(" ", "-")`.
However, [`.replace()` only replaces the first instance when passed a string](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace) as the pattern, so only the first `" "` is replaced with a `"-"`.
This updates to use a regex in `title.replace()` …
> docs: fix 404 when clicking on "Date Range Field"  DemoContainer

- docs/content/meta/TagsInputItem.md
- docs/content/meta/TagsInputRoot.md
- packages/radix-vue/src/TagsInput/TagsInput.test.ts
- packages/radix-vue/src/TagsInput/TagsInputItem.vue
- packages/radix-vue/src/TagsInput/TagsInputItemText.vue
- packages/radix-vue/src/TagsInput/TagsInputRoot.vue
- packages/radix-vue/src/TagsInput/story/TagsInputObject.story.vue
- packages/radix-vue/src/TagsInput/story/_TagsInputObject.vue
Adds support for object in `TagsInput`. See the new [`Object story`](https://github.com/radix-vue/radix-vue/blob/onmax/tags-input-objects/packages/radix-vue/src/TagsInput/story/TagsInputObject.story.vue) to see the code
> This PR is non-breaking
> feat(tagsInput): added support for object in tags input

- packages/radix-vue/src/Calendar/CalendarRoot.vue
Export typo `MultipleCalendarRootProps` and  `SingleCalendarRootProps` used by `CalendarRootProps`.
I was working on build an UI library based on radix-vue/shadcn-vue, this error shows up when build:
This seems a typescript limitation that interface of type alias should also be exposed.
I have also tried:
```ts
interface CalendarRootProps extends MultipleCalendarRootProps, SingleCalendarRootProps {
}
```
which will also work because it's an interface, but I think they are not functionally equivalent.
> feat: export CalendarRoot props

- packages/radix-vue/package.json
From [Typescript DevBlog](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#package-json-exports-imports-and-self-referencing):
> Note that the "types" condition should always come first in "exports".
Fixes #925
> fix: `types` should always come first in `exports`

- packages/radix-vue/src/Dialog/Dialog.test.ts
- packages/radix-vue/src/Dialog/DialogContentImpl.vue
- packages/radix-vue/src/Dialog/DialogRoot.vue
- packages/radix-vue/src/Dialog/DialogTrigger.vue
- packages/radix-vue/src/Dialog/story/DialogExternalTrigger.story.vue
- packages/radix-vue/src/Dialog/story/DialogWithDropdown.story.vue
Closes #921 
Adds a `triggerElement` prop to the DialogRoot so that the user can specify which trigger was used to open the dialog.
> feat: triggerElement prop for DialogRoot

- docs/content/meta/AlertDialogAction.md
- docs/content/meta/AlertDialogCancel.md
- docs/content/meta/AlertDialogDescription.md
- docs/content/meta/AlertDialogTitle.md
- docs/content/meta/AlertDialogTrigger.md
- packages/radix-vue/src/AlertDialog/AlertDialogAction.vue
- packages/radix-vue/src/AlertDialog/AlertDialogCancel.vue
- packages/radix-vue/src/AlertDialog/AlertDialogDescription.vue
- packages/radix-vue/src/AlertDialog/AlertDialogTitle.vue
- packages/radix-vue/src/AlertDialog/AlertDialogTrigger.vue
Correct the documentation about the default values for some of the components in `AlertDialog`.
> Docs(AlertDialog): Fix default values for the components

- docs/content/guides/i18n.md
Resolves https://github.com/radix-vue/radix-vue/issues/875
Update the examples in the Internationalization page to explicitly set the `dir` prop of ConfigProvider to prevent a type error when using `useTextDirection`
> Docs(i18n): update examples with explicit direction

- packages/radix-vue/src/NumberField/index.ts
Hello 👋
Just a small fix that added a missed export of NumberFieldRootEmits. This is needed to create a components like shadcn-vue library do.
> fix(NumberField): added missed export of NumberFieldRootEmits

- packages/radix-vue/src/Calendar/CalendarGrid.vue
- packages/radix-vue/src/Calendar/CalendarNext.vue
- packages/radix-vue/src/Calendar/CalendarPrev.vue
This PR refactors/fixes these two small issues:
- f14f28e9bb0d697aa91c5dd9d28a0bd300a56297: in `CalendarNext` and `CalendarPrev` we are passing the `step` prop to `Primitive` even if it doesn't support it.
- 062c6978262a42a6b7e1428f4bbbfa05269d5a37: in `CalendarGrid`, we assign `aria-disabled` and `aria-read-only` by reading from the root context, but those values are refs into an object, and such are not unwrapped by the compiler.
> Refactor(Calendar): update props management in navigation buttons and grid component 

- packages/radix-vue/src/shared/useForwardPropsEmits.ts
Having type error after upgrade to `v1.8.1`. 
`T` here will parse to `ComputedRef<ComputedRef<T>>` if pass in `ComputedRef<T>`.
e.g.
```ts
const a = computed(() => {
return {
a: 1,
}
})
const test = useForwardPropsEmits(a)
```
will result in 
This due to `UnwrapRef` generic `U` was removed from `useForwardProps` in `v1.8.1`
>  fix: add MaybeRefOrGetter type to useForwardPropsEmits param

- packages/radix-vue/src/NumberField/NumberField.test.ts
- packages/radix-vue/src/NumberField/NumberFieldRoot.vue
Hello,
This PR fixes the issue described in #953 on the NumberField. 
It should now start from the `min` value or `0` on `increment`/`decrement` if the input value is cleared.
> fix(NumberField): always updateModelValue on blur

- packages/radix-vue/src/FocusScope/FocusScope.test.ts
Hello,
Fix #956.
This PR adds `await` for a couple of `userEvent` calls which might have caused the error on the pipeline(after the env teardown).
> fix(FocusScope): add await to userEvent in test

- docs/content/meta/DatePickerField.md
- packages/radix-vue/src/DatePicker/DatePickerField.vue
> feat: exposes modal-value to make date-picker-input optional

- docs/content/meta/TooltipContent.md
- packages/radix-vue/src/Tooltip/TooltipContent.vue
- packages/radix-vue/src/Tooltip/stories/Tooltip.story.vue
Hello,
This PR adds `Presence` to `TooltipContent`, to allow using a close animation. I also added a story to see it in action (feel free to remove or ask me to remove this story if that's not needed).
> fix(Tooltip): added Presence to TooltipContent to allow close animation

- .editorconfig
- eslint.config.mjs
Hello,
This PR fixes #996.
I've enabled both the `typescript` and `vue` plugins on the config to make sure they always get loaded.
I've also added a default `.editorconfig` file so that any editor will maintain spacing and carriage return consistency.
I've also enabled the `import` related rules (I recall those being on before ESLint 9) plus added a rule for `vue` `template` HTML attributes that makes them more readable IMO.
Looking forward to any feedback 🚀
> fix: update eslint configs

- packages/plugins/src/nuxt/index.ts
With Nuxt 4 on the horizon, this updates the module compatibility definition to allow it to be installed on Nuxt v4. (Otherwise Nuxt will indicate the module might not be compatible.)
When Nuxt v4 comes out then you might decide or need to make breaking changes in this module and release a new major, but hopefully the migration should be smoother. 🙏 
👉 You can follow this and other changes in https://github.com/nuxt/nuxt/issues/27613 - please feel free to provide feedback as well!
> chore: indicate compatibility with new v4 major

- packages/radix-vue/src/HoverCard/HoverCardContentImpl.vue
- packages/radix-vue/src/HoverCard/HoverCardRoot.vue
- packages/radix-vue/src/HoverCard/HoverCardTrigger.vue
Hello!
This pr fix the bug of issue https://github.com/radix-vue/radix-vue/issues/994
A hovering ref was added to check after the open delay time if the mouse is still waiting for the content
New behavior:
https://github.com/radix-vue/radix-vue/assets/10001036/b1c84286-05b6-422b-ab27-439518f76e22
> fix(HoverCard): avoid opening for quick hovers

- docs/content/components/editable.md
- packages/radix-vue/src/Editable/EditableInput.vue
Context: https://github.com/radix-vue/radix-vue/issues/1008
Currently editable is very strict and submits on space input, even if submitMode is set to `enter`. This changes it to only enforce shift-space usage when submitMode is `both`.
> fix(Editable): allow space inputs when submitMode is enter

- packages/radix-vue/src/VisuallyHidden/VisuallyHiddenInput.vue
Faced with an issue, when null value passed to Combobox component. The parsedValue in VisuallyHiddenInput doesn't provide correct check for null value
> fix(combobox): when null value passed to VisuallyHiddenInput component

- docs/content/meta/DropdownMenuRadioGroup.md
- docs/content/meta/MenubarRadioGroup.md
- packages/radix-vue/src/Menu/MenuRadioGroup.vue
When using the `DropdownMenuRadioGroup` using `@update:model-value` instead of binding `v-model` we noticed that the payload was type `boolean` when we expected `string`. This type is also in line with similar components (`RadioGroupRoot`).
With this PR the type is updated to reflect the payload value, along with the docs.
> fix(MenuRadioGroup): update:modelValue payload type

- docs/content/meta/EditableRoot.md
- packages/radix-vue/src/Editable/EditableRoot.vue
Hello,
This PR exposes the internal functions on the `EditableRoot` slot to enable programmatic control of the internal state of the `Editable` component.
Should address the use case in #1021.
> feat(Editable): expose editable functions

- packages/radix-vue/src/Pagination/utils.ts
> fix(Pagination): add conditions for 2 siblings edge case

- packages/radix-vue/src/Calendar/Calendar.test.ts
- packages/radix-vue/src/Calendar/story/CalendarFixedWeeksForLocales.story.vue
- packages/radix-vue/src/date/calendar.ts
When fixedWeeks is true and next month starts in another row of Calendar first day was missing:
After the fix:
Fix is quite simple but I've also extended the test case and added a new story for fixedWeeks. 
I do not know if you want to have all fixes covered by a test case but taking in to account that on my machine Calendar tests took 15 seconds before and now 2 seconds were added I would personally not merge my test.
I think the new story is also not providing that much value but it helped me test the fix so I included it as well.
Thank you for this library and for shadcn/vue :)
> fix(Calendar): sometimes first day of next month is missing

- packages/radix-vue/src/Combobox/Combobox.test.ts
- packages/radix-vue/src/Combobox/ComboboxRoot.vue
I think current highlighting functionality is unintuitive.
When the user is removing characters (eg: by backspacing) the highlighted option should always be the first matching option from the dropdown list. It should provide the same behavior as typing, but backwards.
for reference please check [shadcn/ui's combobox](https://ui.shadcn.com/docs/components/combobox) or [headleassui's combobox](https://headlessui.com/react/combobox)
this PR is fixing that behavior.
before:
after the change:
> fix(combobox): when backspacing searchTerm highlight the first available option

- package.json
When I launch story, the console messages push the browser access link to the top, which impacts the debugging experience
> chore: optimize start-up command to automatically open browser with story:dev

- packages/radix-vue/src/Editable/EditableRoot.vue
> fix(Editable): do not submit if editable is not in edit mode

- packages/radix-vue/src/Editable/EditablePreview.vue
So the `update:state` event is triggered with the `edit` state
> fix(Editable): use exposed edit function to trigger edit

- packages/radix-vue/src/Editable/EditableInput.vue
- packages/radix-vue/src/Editable/EditableRoot.vue
Implements #1044.
`Editable` component `input` implementation aligned to `NumberField` input implementation.
> feat(Editable): use Primitive for input to enable textarea usage

- renovate.json
Hello,
This PR adds the `vue` group for updating the dependencies and also adds several packages to the appropriate groups so that Renovate makes less PRs.
> Feat: add packages to vue, lint and build groups

- packages/radix-vue/src/Calendar/CalendarCellTrigger.vue
- packages/radix-vue/src/RangeCalendar/RangeCalendarCellTrigger.vue
Hello,
This PR adjusts the `CalendarCellTrigger`/`RangeCalendarCellTrigger` to depend on the `props.day` value on both its `keydown` and `mousedown` events, therefore improving the consistency of the implementation on both components.
> Fix: improve consistency of calendar cell triggers

- packages/radix-vue/src/Combobox/Combobox.test.ts
- packages/radix-vue/src/Combobox/ComboboxRoot.vue
- packages/radix-vue/src/Combobox/story/_Combobox.vue
- packages/radix-vue/src/Listbox/Listbox.test.ts
- packages/radix-vue/src/Listbox/ListboxRoot.vue
When using `v-model` with `multiple:true`, the `update:modelValue` event doesn't get emitted. Please see the reproduction link: https://codesandbox.io/p/sandbox/radix-vue-combobox-forked-9pqcs3
I noticed this behavior on Listbox and Combobox components. Searching through the code, there doesn't seem to be an issue with other components that accept single or multiple values as vModel. 
Alternatively, Listbox and Combobox components could be refactored to use `useSingleOrMultipleValue` composable (like ToggleGroup or Accordion use), however, the fix was pretty simple, and refactoring would take a lot more time (and I'm also not sure if it is a direction you'd want to go in), so I opted to just fix the problem.
When writing tests for the Listbox with `selectionBehavior: replace`, I found …
> fix(Combobox,Listbox): `update:modelValue` with `multiple:true` does not get emitted

- docs/content/components/calendar.md
- docs/content/meta/CalendarNext.md
- docs/content/meta/CalendarPrev.md
- docs/content/meta/DatePickerNext.md
- docs/content/meta/DatePickerPrev.md
- docs/content/meta/DateRangePickerNext.md
- docs/content/meta/DateRangePickerPrev.md
- docs/content/meta/ListboxRoot.md
- docs/content/meta/RangeCalendarNext.md
- docs/content/meta/RangeCalendarPrev.md
- docs/content/meta/TreeRoot.md
- packages/radix-vue/src/Calendar/CalendarCellTrigger.vue
- packages/radix-vue/src/Calendar/CalendarNext.vue
- packages/radix-vue/src/Calendar/CalendarPrev.vue
- packages/radix-vue/src/Calendar/CalendarRoot.vue
- packages/radix-vue/src/Calendar/useCalendar.ts
- packages/radix-vue/src/RangeCalendar/RangeCalendarCellTrigger.vue
- packages/radix-vue/src/RangeCalendar/RangeCalendarNext.vue
- packages/radix-vue/src/RangeCalendar/RangeCalendarPrev.vue
- packages/radix-vue/src/RangeCalendar/RangeCalendarRoot.vue
- packages/radix-vue/src/RangeCalendar/story/_RangeCalendar.vue
- packages/radix-vue/src/shared/date/index.ts
- packages/radix-vue/src/shared/date/types.ts
Hello,
This PR fully removes the `step` property from the `CalendarNext`/`CalendarPrev` components, plus adjusts the utility functions to take this change into account.
I've marked this PR with the `v2` label to keep track of it.
> refactor: remove calendar step prop

- packages/radix-vue/src/Combobox/ComboboxItem.vue
Looks like it was originally copied from `SelectItem` implementation. So pretty much just fixing a typo.
> Update ComboboxItem error message for empty 'value' prop

- docs/content/meta/ComboboxViewport.md
- docs/content/meta/ConfigProvider.md
- docs/content/meta/ScrollAreaViewport.md
- docs/content/meta/SelectViewport.md
- docs/content/meta/Viewport.md
- packages/radix-vue/src/Combobox/ComboboxViewport.vue
- packages/radix-vue/src/ConfigProvider/ConfigProvider.vue
- packages/radix-vue/src/ScrollArea/ScrollAreaViewport.vue
- packages/radix-vue/src/Select/SelectViewport.vue
- packages/radix-vue/src/Viewport/Viewport.vue
- packages/radix-vue/src/shared/useNonce.test.ts
- packages/radix-vue/src/shared/useNonce.ts
Resolves #1097.
Implemented via existing `ConfigProvider` and additional `useNonce` composable to be used in primitives. Added test to make sure `nonce` still can be overridden locally in place to maintain backwards compatibility.
Also added description to `nonce` prop in related primitives and regenerated docs.
> feat: global nonce value via `ConfigProvider`

- packages/radix-vue/src/Tree/index.ts
This PR adds the missing `TreeItemEmits` export to `Tree/index.ts`
Closes #1115
> fix: export TreeItemEmits

- docs/content/overview/installation.md
Following the instructions here (https://github.com/unplugin/unplugin-vue-components) I think we should use the plural, no?
> Fix unplugin-vue-components installation instruction

- packages/radix-vue/src/Select/SelectItem.vue
The bug was that the aria-selected was only true when the option was also highlighted (isFocused). I looked at how this is done in Combobox (where it's working correctly) and adjusted it accordingly.
> Fix the aria-selected attribute for SelectItem

- docs/content/meta/ToastRoot.md
- packages/radix-vue/src/Toast/Toast.test.ts
- packages/radix-vue/src/Toast/ToastRoot.vue
- packages/radix-vue/src/Toast/ToastRootImpl.vue
This allows retrieving the duration of the toast with knowledge of the global default that may have been set in ToastProvider.
> feat(Toast): expose toast duration in slot

- packages/radix-vue/src/Splitter/SplitterGroup.vue
- packages/radix-vue/src/Splitter/SplitterPanel.vue
fix #1112 
after I update `eagerValuesRef` . `Splitter` will be reset to default size. I'm not sure is this a bug or feature.
> fix(Splitter): splitter-panel works based on the old layout after props change

- packages/radix-vue/src/Combobox/Combobox.test.ts
- packages/radix-vue/src/Combobox/ComboboxInput.vue
- packages/radix-vue/src/Combobox/story/_Combobox1k.vue
This is a hacky solution that fixes #1040 and works fine with 100+ options in a combobox. As v2 is being developed and the combobox gets reworked to better handle these cases, I assume a better solution will be implemented - the purpose of this fix is to unblock people stuck on 1.8.3 due to this bug.
> fix(Combobox): workaround for maximum recursion update issues

- docs/content/components/date-range-picker.md
- docs/content/components/range-calendar.md
- packages/radix-vue/src/RangeCalendar/RangeCalendarCellTrigger.vue
- packages/radix-vue/src/RangeCalendar/RangeCalendarRoot.vue
- packages/radix-vue/src/RangeCalendar/useRangeCalendar.ts
> feat(RangeCalendar): add highlighted range bounds data attributes on cell trigger

- packages/radix-vue/src/DateField/DateFieldRoot.vue
- packages/radix-vue/src/DateField/story/DateFieldDefault.story.vue
- packages/radix-vue/src/DateField/utils/segment.ts
- packages/radix-vue/src/DateRangeField/DateRangeFieldRoot.vue
> fix(DateField): rebuild focusable element Set on locale change

- packages/radix-vue/src/Calendar/Calendar.test.ts
- packages/radix-vue/src/Calendar/CalendarCellTrigger.vue
- packages/radix-vue/src/Calendar/CalendarNext.vue
- packages/radix-vue/src/Calendar/CalendarPrev.vue
- packages/radix-vue/src/Calendar/story/CalendarChromatic.story.vue
- packages/radix-vue/src/DateField/DateField.test.ts
- packages/radix-vue/src/DateField/DateFieldRoot.vue
- packages/radix-vue/src/DateField/useDateField.ts
- packages/radix-vue/src/DatePicker/DatePicker.test.ts
- packages/radix-vue/src/DatePicker/DatePickerTrigger.vue
- packages/radix-vue/src/DateRangePicker/DateRangePicker.test.ts
- packages/radix-vue/src/DateRangePicker/DateRangePickerTrigger.vue
- packages/radix-vue/src/RangeCalendar/RangeCalendar.test.ts
- packages/radix-vue/src/RangeCalendar/RangeCalendarCellTrigger.vue
- packages/radix-vue/src/RangeCalendar/RangeCalendarNext.vue
- packages/radix-vue/src/RangeCalendar/RangeCalendarPrev.vue
- packages/radix-vue/src/RangeCalendar/story/RangeCalendarChromatic.story.vue
- remove tabindex when disabled
- disable button when the root was disabled
- prevent focusable on cell trigger when disabled
> fix(Dates): disable state not affect tabindex and relevant button

- docs/components/demo/Calendar/css/styles.css
- docs/components/demo/CalendarSelect/css/styles.css
- docs/components/demo/CalendarYearIncrement/css/styles.css
- docs/components/demo/DatePicker/css/styles.css
- docs/components/demo/DateRangePicker/css/styles.css
- docs/components/demo/RangeCalendar/css/styles.css
Add missing semicolon in CalendarGridRow class styling within demo.
> fix: add missing semicolon in CalendarGridRow class styling within demo

- docs/content/components/tree.md
- docs/content/meta/TreeRoot.md
- packages/radix-vue/src/Tree/Tree.test.ts
- packages/radix-vue/src/Tree/TreeItem.vue
- packages/radix-vue/src/Tree/TreeRoot.vue
Adds a new optional prop to `<TreeRoot />`, `getChildren`, which allows the user to provide a custom list of children. This is helpful when you have a custom data schema.
Fixes #1139.
Also adds new tests and updates the docs to account for the change.
> feat(Tree): allow custom children schema

- docs/content/components/combobox.md
Updates an example in the docs  to clarify the need for `displayValue` prop when binding an object.
Helps to avoid confusion e.g. #1190.
> docs(Combobox): update "Binding objects as values" example

- packages/radix-vue/src/Popper/PopperContent.vue
**Problem**
When floating-ui returned isPositioned=true, radix-vue immediately emitted an event to focus on the selected item in the Select component. However, at this point, the PopperContent element did not yet have the correct transform CSS property set, resulting in the Popper being positioned at coordinates (0, -200%).
**Solution**
I changed the watchEffect to watchPostEffect to ensure that the event is emitted only after the DOM has been updated and the Popper is correctly positioned on the page (e.g., at coordinates 84px, 231px). This ensures that focusSelectedItem is called only after the Popper has been properly positioned.
**Changes**
- Replaced watchEffect with watchPostEffect to emit the positioning event after DOM updates.
> fix(Popper): use `watchPostEffect` for `placed` update

- packages/radix-vue/src/Tabs/TabsIndicator.vue
**Problem**
When the dir attribute of the page was changed dynamically, the indicator position in the Tabs component did not adjust to reflect the new text direction. This caused the indicator to remain in the incorrect position, resulting in a poor user experience.
**Solution**
I updated the Tabs component to correctly update the indicator position when the dir attribute of the page changes. This ensures that the indicator is always positioned correctly according to the current text direction.
**Changes**
- Added a watcher for the dir attribute to dynamically update the indicator position in the Tabs component when the text direction changes.
> fix(Tabs): recalculate `tabs indicator position` on direction change

- docs/content/meta/StepperRoot.md
- packages/radix-vue/src/Stepper/StepperRoot.vue
This PR adds next step and prev step functions to the `StepperRoot` slot props.
It also fixes a bug on the `goToStep` function which was trying to get an attribute on an out-of-bounds element.
> feat(Stepper): add next and prev step slot function

- packages/radix-vue/src/DateField/DateFieldRoot.vue
- packages/radix-vue/src/DatePicker/DatePickerRoot.vue
- packages/radix-vue/src/DateRangeField/DateRangeFieldRoot.vue
- packages/radix-vue/src/DateRangePicker/DateRangePickerRoot.vue
- packages/radix-vue/src/RangeCalendar/RangeCalendarCellTrigger.vue
- packages/radix-vue/src/RangeCalendar/RangeCalendarRoot.vue
Closes #1207.
PR fixes:
-  a regression where the `Calendar`-type components were not updating the `DateField`-type components in the `DatePicker` components
- setting the same date on a `DateField`-type component was setting an erroneous invalid state on the field
> feat(RangeCalendar): enable same date selection

- packages/radix-vue/src/Splitter/SplitterGroup.vue
- packages/radix-vue/src/Splitter/story/SplitterDirection.story.vue
- packages/radix-vue/src/Splitter/utils/registry.ts
When toggling direction on `SplitterGroup`
```
<SplitterGroup :direction="direction">
...
</SplitterGroup>
```
resize cursor styles stick to its initial values (https://stackblitz.com/edit/gdyqde?file=src%2FApp.vue)
Made `SplitterGroup` to provide a reactive `direction`
> fix(Splitter): not updating `SplitterResizeHandle` cursor style properly when `direction` changes

- packages/radix-vue/src/Combobox/ComboboxContentImpl.vue
the `ComboboxInput` was hidden away wrongly. We should hide away other element other than `parentElement`
> fix(Combobox): error log when opening content

- packages/radix-vue/src/Listbox/ListboxVirtualizer.vue
- packages/radix-vue/src/Tree/TreeVirtualizer.vue
Expose the virtualizer to the default slot of ListboxVirtualizer and TreeVirtualizer.
This allows the height of the virtualized element to be dynamically calculated if necessary or styled.
```vue
<template>
<ListboxVirtualizer
v-slot="{ option, virtualizer, virtualItem }"
... ...
>
<ListboxItem
:class="virtualItem.index % 2 === 0 && 'bg-accent/50'"
@vue:mounted="(node: VNode) => virtualizer.measureElement(node.el as Element)"
... ...
>
<div>... ... ...</div>
</ListboxItem>
</ListboxVirtualizer>
</template>
```
resolve #1266
> Expose virtualizer and virtualized items

- docs/content/docs/guides/migration.md
To assist with the upgrade from radix-vue to reka-ui, we have added features that utilize codemods to automatically update your code to many of the new updates and patterns. 
These codemods include breaking changes which aren't implemented interally but have to updated across multiple repositories using the framework.
These will run the following codemods from the radix-vue Codemod repository:
- **Remove filter-function props**
- **Rename controlled state to v-model**
- **Remove deprecated step prop**
Combobox has been refactored and improve to support better custom filtering. 
- Additional Details
- Replace searchTerm props of Root to Input's v-model
- https://go.codemod.com/3lqPTdS
Replace v-model:checked, v-model:pressed with more familiar API for form component.
- Additional Details
- …
> added codemods to docs

- packages/radix-vue/src/Combobox/Combobox.test.ts
- packages/radix-vue/src/Combobox/ComboboxRoot.vue
This PR is my attempt of fixing the bug described in #1278 
~~Important: [the test case here is a false-positive](https://github.com/radix-vue/radix-vue/compare/main...ragulka:1278-bug-stop-enter-event-propagation-in-combobox?expand=1#diff-336ad141037fb1bc99cda0417410f50e54953fbce0363fe53d5164094230a814R343-R345): when I remove the `event.stopPropagation()` line, it still passes. I'm not surer why - I don't have too much experience with vitest and if event bubbling actually happens in the test environment?~~
Since we're not using a real browser, the enter event bubbling up to form is not causing a form submit in tests. So, instead of testing for the handleSubmit not to be called, I updated the test to check if the enter event bubbled up to the form.
With this change, removing the …
> fix(Combobox): stop event propagation on enter

- docs/components/Callout.vue
- docs/components/examples/ComboboxTextarea/list.ts
- docs/content/docs/guides/migration.md
This PR updates migration codemods:
- command names
- improves doc styling
- adds contextual links
> docs: update migration codemods

- docs/content/components/popover.md
The WAI Aria documentation link points to a non existent page, so I have updated it to the correct one.
> Update: Fixed WAI Aria Link in popover.md

- packages/radix-vue/src/Splitter/utils/stackingOrder.ts
Fixes https://github.com/radix-vue/radix-vue/issues/1305.
`a` and `area` element can have `host` property.
> fix(Splitter): fix getParent()

- packages/radix-vue/src/RovingFocus/RovingFocusItem.vue
- packages/radix-vue/src/RovingFocus/utils.ts
This PR fixes RovingFocusItem getting the rootNode when using radix-vue in a shadow dom.
Fixes: https://github.com/radix-vue/radix-vue/issues/1003 
Thanks @sunnylost for the detailed fix
> fix: root node for RovingFocusItem when shadowRoot

- packages/radix-vue/src/Listbox/ListboxRoot.vue
Related to https://github.com/radix-vue/radix-vue/issues/1296, but this is not a fix.
When the `onleave()` event is triggered, the element may no longer exist in the DOM tree. As a result, if you try to use the Tab key to focus on it again, the focus will not move to the next item but will instead select the entire list.
> fix(Listbox): check if a dom is still associated with the document

- packages/radix-vue/src/shared/useGraceArea.ts
In Popup windows, the tooltip content wasn't closing after moving from the area, only after going back to the original window and moving the pointer there.
https://github.com/user-attachments/assets/45f94c06-1b27-469c-9b95-b21d7fd9075a
> fix(Tooltip): use trigger's `ownerDocument` to track `pointermove`

- .histoire/tailwind.config.js
- packages/core/src/NavigationMenu/story/NavigationMenuAlignment.story.vue
- packages/core/src/NavigationMenu/story/NavigationMenuBasic.story.vue
- packages/core/src/NavigationMenu/story/NavigationMenuDemo.story.vue
- packages/core/src/NavigationMenu/story/NavigationMenuSubmenus.story.vue
- packages/core/src/NavigationMenu/story/NavigationMenuViewport.story.vue
- packages/core/src/Popper/PopperContent.vue
When I run `dev:story`, I notice there's a warning that says:
```
The class `duration-[250ms]` is ambiguous and matches multiple utilities.
```
According to https://github.com/jamiebuilds/tailwindcss-animate/pull/46, right now we can't use  arbitrary values for `duration`.
> fix: fix invalid duration class name

- docs/.vitepress/layouts/showcase.vue
-Original: my-16 md:my-26
-Correction: my-16 md:my-24 (Tailwind CSS uses multiples of 4 for spacing, so my-26 is not valid; it should be my-24.)
> Fix: Incorrect my spacing utility class

- docs/components/demo/CalendarSelect/css/index.vue
The locale should be in lowercase for the language tag according to the BCP 47 standard. It should be 'ar-EG' instead of 'AR-EG'.
> doc: Update Locale Identifier for Arabic

- packages/core/vite.config.ts
The presence of `/` prefix in the constant build entry breaks the build. It works fine when removed :)
> fix: fix path to constant build entry

- docs/components/demo/Calendar/css/styles.css
The color is already defined the line before & it shouldn't have the unit "px".
> Update styles.css for Calendar - color

- packages/radix-vue/src/Accordion/AccordionContent.vue
- Add forceMount prop to AccordionContent component
- Align component behavior with radix-react
- Allow users to control content rendering even when accordion item is closed
> fix(AccordionContent): add forceMount prop

- docs/content/components/stepper.md
- packages/radix-vue/src/Stepper/StepperItem.vue
- packages/radix-vue/src/Stepper/StepperRoot.vue
Not sure if it was intended, but the term 'tab' is used instead of 'step' in the Stepper component.
> fix(docs): typo in Stepper component

- packages/radix-vue/src/Listbox/ListboxRoot.vue
Because nextTick is added in #1331, if the listbox component gets removed from the dom, an error occurs.
Link to repro: https://stackblitz.com/edit/7jpwyi-yem3zd?file=src%2FApp.vue - checkout the logs in the console
> fix(Listbox): handle currentElement not in dom on focusout

- docs/.vitepress/plugins/ComponentPreview.ts
> fix: dev on Windows not show preview component codes

- packages/radix-vue/src/Pagination/Pagination.test.ts
- packages/radix-vue/src/Pagination/PaginationFirst.vue
- packages/radix-vue/src/Pagination/PaginationLast.vue
- packages/radix-vue/src/Pagination/PaginationListItem.vue
- packages/radix-vue/src/Pagination/PaginationNext.vue
- packages/radix-vue/src/Pagination/PaginationPrev.vue
- packages/radix-vue/src/Pagination/story/_Pagination.vue
Pagination buttons (like prev/next) can become any HTML element, for example `<a>`, which, unlike `<button>`, doesn't support `disabled` attribute and still emits `click` events.
If a pagination button component is considered disabled, but rendered as a non-button HTML element, clicking it may update the component's state in a bad way (for example, set the current page to 0 after clicking the "<" button when being on the first page).
This PR adds `!disabled &&` conditions to all pagination buttons components' `click` event handlers.
> fix(Pagination): ignore clicks if pagination button is disabled

- packages/radix-vue/src/DateField/DateFieldRoot.vue
- packages/radix-vue/src/DateRangeField/DateRangeFieldRoot.vue
> fix(DateField): Reset field segments when model value is undefined

- packages/radix-vue/src/shared/useBodyScrollLock.ts
> fix: bodyScrollLock not working on safari

- packages/radix-vue/src/Toast/ToastRootImpl.vue
This is a follow-up from https://github.com/nuxt/ui/issues/2665
Currently the Toast's duration only starts the timer if false or infinite.
But having a negative duration should also trigger a Toast without a timer.
> fix(Toast): negative duration

- packages/core/src/Checkbox/CheckboxRoot.vue
Typing of Checkbox `emit('update:modelValue')` should be `boolean | 'indeterminate'` instead of `AcceptableValue`.
> [V2] Fix CheckboxRoot update:modelValue typing

- packages/core/vite.config.ts
This PR supersedes and closes #1102 
It does not use the same approach as proposed in #1102 however; seeing the current v2 build uses `preserveModules`. However, because of how the SFC gets split in multiple virtual chunks this causes a lot of unwanted files to clutter the build making it larger than it needs to be.
The approach proposed in this PR mitigates it by using manualChunks to achieve the intended result of a 1:1 mapping between Vue files and the resulting JS files. A little hack has been introduced as well to properly name chunk files with the right file extension and without a hash.
Minification has been disabled: along with the drop of hashes the intent is to make eventual [dependency patches](https://pnpm.io/cli/patch) less brittle (see last comment of #908 for a use-case). …
> chore: improve build

- docs/content/components/dialog.md
current link is broken and gives a 404 error. new or updated link has a dash, think they also have a redirect without a dash but needs the forward slash at the end for it to work.
> Update ARIA broken link dialog.md

- packages/core/src/Combobox/ComboboxItem.vue
Reverting this as it was on `main` branch: https://github.com/unovue/radix-vue/blob/main/packages/radix-vue/src/Combobox/ComboboxItem.vue#L94 because I encountered an issue when passing an array of booleans in items and binding this to the `ComboboxItem` value prop.
> fix(ComboboxItem): revert `props.value` check

- packages/core/src/Menu/MenuContentImpl.vue
In v2, the new PopperContent `positionStrategy` prop is not forwarded in MenuContent.
> fix(Menu): Pass `positionStrategy` prop to PopperContent

- packages/radix-vue/src/Primitive/Primitive.ts
- packages/radix-vue/src/Primitive/Slot.ts
Hi there!
Thanks for this great library. As I scrolled through the documentation, I kept seeing this tiny spelling error, since the `Fragment` props are inherited by almost all components.
Is this PR of substance? No. This PR pales in comparison to your amazing work. Nevertheless, I just wanted to contribute this little grammar fix.
> chore: fix grammar in `Fragment` props JSDoc comment

- packages/core/src/Combobox/ComboboxItem.vue
- packages/core/src/Combobox/ComboboxRoot.vue
closes #1234
This pr fixes when `rootContext.isVirtual.value || rootContext.ignoreFilter.value || !rootContext.filterState.search` is false, the item will never add into `allItems` map.
To reproduce this bug, create a async combobox (e.g. the one in the story), before opening the dropdown, give any value to search query.
<hr />
Added an event listener to apply filter when `allItems` size changes.
\* It uses `watch` rather than `watchDebounced` even the items are set one by one because it's handled by [vue `watch`](https://vuejs.org/guide/essentials/watchers.html#callback-flush-timing)
> fix(combobox/item): fix some items not add into allItems map

- packages/core/src/TimeField/TimeFieldRoot.vue
- packages/core/src/shared/date/parser.ts
Fixes #1425.
Related to #1450.
> fix(TimeField): initial TimeField segments based on `granularity`

- packages/radix-vue/src/shared/useBodyScrollLock.ts
Fixes type error of useBodyScrollLock introduced in https://github.com/unovue/radix-vue/pull/1428.
`TypeError: Argument 1 ('element') to Window.getComputedStyle must be an instance of Element`.
Apparently, not every target of touchmove event has to be Element. Also good example of why type casting should be avoided.
> fix: useBodyScrollLock type error

- packages/radix-vue/src/shared/useFocusGuards.ts
Violates Content-Security-Policy unless `style-src: 'unsafe-inline'` is permitted otherwise. (from radix-ui)
> fix: remove use of `cssText` in focus-guards

- packages/core/src/Menu/MenuContentImpl.vue
This PR adds the `reference` prop in `PopperContent` from `MenuContentImpl` to follow the documentation guidelines (at least for [DropdownMenu](https://reka-ui.com/docs/components/dropdown-menu#content) and [ContextMenu](https://reka-ui.com/docs/components/dropdown-menu#content)) where you can add `:reference` in the `Content` Component to replace the trigger. 
This enables the functionality to add custom locations for both Components.
> fix: pass reference prop to PopperContent

- docs/components/demo/NavigationMenu/tailwind/index.vue
- docs/content/docs/components/navigation-menu.md
- packages/core/src/NavigationMenu/NavigationMenuContent.vue
- packages/core/src/NavigationMenu/NavigationMenuIndicator.vue
- packages/core/src/NavigationMenu/story/NavigationMenuBasic.story.vue
Instead of using custom CSS, the `NavigationMenuIndicator` should rely on custom properties, similar to what [`TabsIndicator`](https://reka-ui.com/docs/components/tabs#indicator) is using.
Closes https://github.com/unovue/radix-vue/issues/1470
> feat(NavigationMenu)!: replace hardcoded CSS values with custom properties

- docs/content/docs/components/combobox.md
See #1496 for details.
Added:
- a warning that items must be filtered before passing to the virtualizer
- link to the virtualization guide
- an example of working virtualizer usage
> docs: Add more ComboboxVirtualization documentation and examples

- packages/core/src/Select/SelectItem.vue
I've implemented a `select` event/emit on the `SelectItem` so it's consistent with `Listbox/Combobox`.
This is especially important when using `multiple` because we cannot rely on `update:modelValue` as we only need the specific item that was last selected.
Let me know if you have any questions or objections!
> feat(SelectItem): Emit a select event when an option is selected

- packages/radix-vue/src/Toast/ToastRootImpl.vue
I'm currently fixing accessibility for our app and migrating to Radix. I struggled to make screen readers announce toasts and I think I found the culprit.
`aria-atomic` attribute specifically needs the `true` value to be read by screen readers, and VoiceOver requires the `role` to be set as `alert` for some reason.
Also, `announceTextContent` seems to display content as an array which is weird when it's announced:
VoiceOver:
NVDA:
It's done on purpose (cf. https://github.com/unovue/radix-vue/blob/main/packages/radix-vue/src/Toast/utils.ts#L77-L78) but VoiceOver actually reads `"3"` as `three inches` for instance, because in our case we have a `strong` element on the number but there's no reason to make a pause between those words.
Setup: 
* NVDA + Firefox + Windows
* VoiceOver + Safari + …
> Fix screen readers announcing toasts

- README.md
Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [Radix Vue Guru](https://gurubase.io/g/radix-vue) to Gurubase. Radix Vue Guru uses the data from this repo and data from the [docs](https://radix-vue.com) to answer questions by leveraging the LLM.
In this PR, I showcased the "Radix Vue Guru", which highlights that Radix Vue now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if you …
> Introducing Radix Vue Guru on Gurubase.io

- docs/content/components/editable.md
- packages/radix-vue/src/Editable/Editable.test.ts
- packages/radix-vue/src/Editable/EditableInput.vue
- packages/radix-vue/src/Editable/EditableRoot.vue
I have faced some issues with understanding how to make a field editable and not change `v-model` when editing and found this example in the Histoire files of the project, I think that this would be useful for others 😉
> feat(Editable): update model value only on submit

- packages/radix-vue/src/Checkbox/Checkbox.test.ts
- packages/radix-vue/src/Checkbox/CheckboxRoot.vue
Fixes https://github.com/unovue/radix-vue/issues/1595
This pull requests addresses the issue that the CheckboxRoot component always sets the `aria-required` attribute to false regardless of what the `required` props is.
> Fix aria-required not set to required prop value for Checkbox

- packages/radix-vue/src/PinInput/PinInputInput.vue
This resolves the issue I discovered here: https://github.com/unovue/radix-vue/issues/1605
I have a reproduction example app (https://stackblitz.com/edit/bhw6xwfr-hcdmactw?file=src%2FApp.vue,package.json) but I failed to reproduce it in the unit tests :(
> fix(PinInput): error throw from resetPlaceholder's nextTick if component not in the DOM anymore

- packages/radix-vue/src/DateField/DateFieldRoot.vue
- packages/radix-vue/src/DatePicker/DatePickerField.vue
- packages/radix-vue/src/DatePicker/DatePickerRoot.vue
- packages/radix-vue/src/DatePicker/story/DatePickerDefault.story.vue
- packages/radix-vue/src/DateRangeField/DateRangeFieldRoot.vue
- packages/radix-vue/src/DateRangePicker/DateRangePickerRoot.vue
> fix(DatePicker): set placeholder based on modelValue

- packages/radix-vue/src/RangeCalendar/RangeCalendarRoot.vue
> fix(RangeCalendar): enable modelValue to be undefined and refactor combined watch condition

- packages/radix-vue/src/DateField/DateFieldRoot.vue
- packages/radix-vue/src/DatePicker/DatePicker.test.ts
This resolves https://github.com/unovue/radix-vue/issues/1618.
Again, I failed to reproduce the issue in unit tests. I tried this, unsuccessfully:
```ts
it('does not throw when selecting the same date twice', async () => {
const { user, trigger, getByTestId, rerender } = setup({
datePickerProps: { modelValue: calendarDate },
emits: { 'onUpdate:modelValue': (data: DateValue) => rerender({ modelValue: data }) },
})
await user.click(trigger)
const selectedDay = getByTestId('calendar').querySelector<HTMLElement>('[data-selected]')!
await user.click(selectedDay)
})
```
> fix(DatePicker): error when unselecting a date

- packages/radix-vue/src/shared/useBodyScrollLock.ts
Follow-up to  #1462, which was not comprehensive solution enough to fix occuring type errors.
> fix: remove type casting in useBodyScrollLock (radix-vue)

- packages/radix-vue/src/shared/useForwardExpose.test.ts
- packages/radix-vue/src/shared/useForwardExpose.ts
This fixes #1631. 
This makes exposing the targeted element with `useForwardExpose` possible.
> fix(useForwardExpose): fix #1631

- packages/core/src/RovingFocus/RovingFocusItem.vue
Calling `useId()` conditionally leads to issues when using Reka's based RadioGroup in [Historie](https://histoire.dev/):
```
runtime-core.esm-bundler.js:1488 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
at useId (useId.ts:22:29)
at ComputedRefImpl.fn (RovingFocusItem.vue:27:46)
at ComputedRefImpl.fn (RovingFocusItem.vue:29:47)
```
This also happens in Reka's Historie. To reproduce:
- Start Historie
- Open RadioGroup story
- Open another story
- Go back to RadioGroup
- See error in console
> fix: do not call useId() conditionally

- docs/.vitepress/components/DocCommunity.vue
Fix hover style for light mode theme. When in light mode theme, the original hover color is white, if you hover on the link, you will see nothing.
> docs: Update DocCommunity.vue

- packages/core/src/Combobox/ComboboxRoot.vue
The default value of combobox does not work.
The concrete problem seems to be operator precedence, since the null coalescing operator has higher precedence (3) than the ternary operator (2). [[1](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_precedence#table)]
So if you would supply a `defaultValue` of `"some value"` and leave `multiple` to be `false`, then it would evaluate to:
```js
"some value" ?? false ? [] : undefined
// outputs []
// but it should be "some value"
```
With this pull request, the evaluation would change to:
```js
"some value" ?? (false ? [] : undefined)
// outputs "some value"
```
Also see implementation of `SelectRoot.vue`, where `defaultValue` works:
https://github.com/unovue/reka-ui/blob/1f685625029187943ec456764756394e2d399520 …
> fix(ComboboxRoot): properly initialize defaultValue

- packages/core/src/Collapsible/index.ts
Exported missing `CollapsibleContentEmits` type from its Vue component for improved type safety and usage consistency.
Fixes Issue #1694
> fix: export CollapsibleContentEmits type

- docs/content/meta/Toggle.md
- docs/content/meta/ToggleGroupItem.md
- packages/core/src/Toggle/Toggle.vue
- packages/core/src/ToggleGroup/ToggleGroupItem.vue
The state of the toggle should be accessible within slot props, not just within CSS.
> feat(Toggle): Pass state of toggle to slot props

- packages/core/src/NavigationMenu/NavigationMenuViewport.vue
If `NavigationMenuViewport` is dynamically unmounted, the `NavigationMenuRoot` is never updated in consequence. This pull request resolves this.
I need this in my project to allow my menu to show it's menu item content differently depending if the menu is collapsed or not. I implemented it by having a `v-if` on my `NavigationMenuViewport` bound to the `collapsed` prop.
> fix(NavigationMenu): allow viewport unmount to set menuContext viewport to null

- docs/content/meta/NumberFieldRoot.md
- packages/core/src/NumberField/NumberField.test.ts
- packages/core/src/NumberField/NumberFieldRoot.vue
When a `step` prop is defined (which is generally the case, since it has a default of `1`) for `NumberFieldRoot` component, the value is automatically snapped to an increment of that step. This can be problematic when the step value is intended as a shortcut to help the user make changes, but not necessarily a requirement of the field.
For example, it is commonly desired for a number field to use a step of `1` if whole integers are the most common input, but still allow a user to enter a value such as `1.5` if necessary.
This pull request adds a new prop called `stepSnapping` which controls whether this value to step snapping occurs. The default value is `true` for backwards compatibility, but can be set to `false` to disable the snapping behaviour (does not affect snapping/clamping to …
> feat(NumberField/NumberFieldRoot): add stepSnapping prop to disable snapping values to step (#1593)

- packages/core/src/TagsInput/TagsInputItemDelete.vue
Since `modelValue` is somehow deeply wrapped when using `useVModel` it might not be the same reference as the `value` props passed to `TagsInputItem`. 
We found this the hard way when following [Combobox with TagsInput](https://reka-ui.com/examples/combobox-tags-input) example:
```
<template>
<ComboboxRoot
v-model="values"
>
<ComboboxAnchor>
<TagsInputRoot
v-model="values"
delimiter=""
>
<TagsInputItem
v-for="item in values"
:key="item"
:value="item"  <-- this item is no longer the same reference as i.e. values[0]
```
> fix(TagsInput): fix comparing model values when looking for current item index in TagsInputItemDelete

- docs/content/showcase.md
It should be in v2 as well. I didn’t notice that the showcase button redirect is in v1. 
Reference: https://github.com/unovue/reka-ui/pull/1731.
Thanks again 💚.
> docs(Showcase): add `una-ui` to the packages section

- packages/core/src/Calendar/Calendar.test.ts
- packages/core/src/Calendar/CalendarCellTrigger.vue
- packages/core/src/RangeCalendar/RangeCalendarCellTrigger.vue
Hello @zernonia 
Just realised this morning that the cell trigger focus calculations were breaking if the `numberOfMonths` was greater than 2. 😅  Sorry about that. This should fix it for good 🙏🏻
> fix(Calendar): handle number of months > 2

- packages/core/src/Calendar/Calendar.test.ts
- packages/core/src/Calendar/CalendarCellTrigger.vue
- packages/core/src/RangeCalendar/RangeCalendar.test.ts
- packages/core/src/RangeCalendar/RangeCalendarCellTrigger.vue
- packages/core/src/RangeCalendar/story/_RangeCalendar.vue
Fixes bugs in `Calendar` and `RangeCalendar` when navigating the focus into months that contain the `minValue` or `maxValue`. I added unit tests that make sure it works for both components with `numberOfMonths=1` and `numberOfMonth=2`.
> fix(Calendar): minValue and maxValue navigation issues

- packages/core/src/Calendar/Calendar.test.ts
- packages/core/src/Calendar/CalendarCellTrigger.vue
- packages/core/src/Calendar/utils.ts
- packages/core/src/RangeCalendar/RangeCalendarCellTrigger.vue
This PR builds upon #1750 and fixes calendar navigation when a date is disabled.
Before:
https://github.com/user-attachments/assets/ad7f9105-9dc0-4f94-97dd-db38c179dc15
After:
https://github.com/user-attachments/assets/84db2933-ee91-42bc-838e-70e2cb185d8c
> fix(Calendar): handle keyboard navigation with disabled dates

- packages/core/README.md
Convert 'Join our discord' into Unovue's Discord invite link since I think a lot of people (including myself) expected it to be that way.
> chore/readme: convert 'join our discord' into a link

- packages/core/src/Primitive/Primitive.ts
Probably not a big deal, but it could save some performance along the way.
> perf(primitive): don't redeclare SELF_CLOSING_TAGS in each instance

- packages/core/src/Accordion/AccordionContent.vue
Fix: https://github.com/unovue/reka-ui/issues/1768
I think the problem is just the prop not being passed down to the underlying component.
> fix(accordion-content): pass `as` prop down to CollapsibleContent

- packages/core/src/Presence/usePresence.ts
I found that getAnimationName(node.value) returns the string 'undefined', which prevents isPresent from properly updating to false.
> fix(usePresence): handle undefined animation name in presence hook

- packages/core/src/Select/Select.test.ts
- packages/core/src/Select/SelectTrigger.vue
- packages/core/src/Select/utils.ts
When the select component is set as multiple and the array of selected options is empty, the data-placeholder wasn't set on the SelectTrigger component. This PR should fix this.
> fix(Select): add data-placeholder for empty array

- packages/core/src/Select/SelectItem.vue
As reported in #1374, `SelectItem` fails inside tests. The fix seems quite straightforward, and I have tested that it works.
> #1374 Fix SelectItem focus in tests

- packages/core/src/Combobox/ComboboxRoot.vue
This pull request removes the `@ts-expect-error` from here:
https://github.com/unovue/reka-ui/blob/c9f4a2a2161f82fd1f6250c4a378ded535a7c641/packages/core/src/Combobox/ComboboxRoot.vue#L95-L100
And converts it to the following:
https://github.com/unovue/reka-ui/blob/69da1b1597c076cbb9263a2f6cbf05c761101a14/packages/core/src/Combobox/ComboboxRoot.vue#L95-L99
I hope this is acceptable.
In order to understand this change, we need to have a look at how `useVModel` infers the type of the `defaultValue` option.
The `useVModel` function takes 3 generic parameters, of which the first two are important in this case, since they are used for the type of the `defaultValue` option:
1. `P extends object`
2. `K extends keyof P`
3. `Name extends string` (unimportant in this case, but included for …
> fix(ComboboxRoot): fix ignored type error

- packages/core/src/Popper/PopperContent.vue
There is some cases when you need to shift position according to boundary but not completely flipping to the other sides (e.g. popovers with contents only making sense underneath a field). I have added `sideFlip` & `alignFlip` props which correspond to [mainAxis](https://floating-ui.com/docs/flip#mainaxis) & [crossAxis](https://floating-ui.com/docs/flip#crossaxis) floating-ui `flip()` options. At first I was thinking of an unique property to disable flipping completely but two prop for each axis seems better for more fine-grained options.
> feat(Popper): Add flip options props
